/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository:
https://github.com/MichaelLing83/Obsidian-flashcards
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  FlashcardView: () => FlashcardView,
  default: () => FlashcardsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  deckFolder: "",
  newCardsPerDay: 20,
  maxReviewsPerDay: 100
};
var DEFAULT_EASE = 2.5;
var MIN_EASE = 1.3;
var MS_PER_DAY = 864e5;
var VIEW_TYPE_FLASHCARD = "flashcard-study-view";
var QUALITY = [1, 3, 4, 5];
function nextInterval(rating, rec) {
  const q = QUALITY[rating];
  if (q < 3) return 1;
  if (rec.repetitions === 0) return 1;
  if (rec.repetitions === 1) return 6;
  return Math.round(rec.interval * rec.easeFactor);
}
function applyRating(rec, rating) {
  const q = QUALITY[rating];
  const interval = nextInterval(rating, rec);
  const repetitions = q < 3 ? 0 : rec.repetitions + 1;
  let easeFactor = rec.easeFactor + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02));
  if (easeFactor < MIN_EASE) easeFactor = MIN_EASE;
  const dueDate = Date.now() + interval * MS_PER_DAY;
  return { ...rec, repetitions, easeFactor, interval, dueDate };
}
function formatInterval(rating, rec) {
  const d = nextInterval(rating, rec);
  if (d < 2) return "1d";
  if (d < 7) return `${d}d`;
  if (d < 30) return `${Math.round(d / 7)}w`;
  if (d < 365) return `${Math.round(d / 30)}mo`;
  return `${Math.round(d / 365)}y`;
}
function stripFrontmatter(raw) {
  if (!raw.startsWith("---")) return raw;
  const end = raw.indexOf("\n---", 3);
  if (end === -1) return raw;
  return raw.slice(end + 4).trim();
}
var FlashcardView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.queue = [];
    this.idx = 0;
    this.revealed = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_FLASHCARD;
  }
  getDisplayText() {
    return "Flashcards";
  }
  getIcon() {
    return "brain";
  }
  async onOpen() {
    await this.startSession();
  }
  /** (Re-)build the study queue and render the first card. */
  async startSession() {
    await this.buildQueue();
    this.idx = 0;
    this.revealed = false;
    this.render();
  }
  // ── Queue building ─────────────────────────────────────────────────────
  async buildQueue() {
    const { deckFolder, newCardsPerDay, maxReviewsPerDay } = this.plugin.settings;
    if (!deckFolder) {
      this.queue = [];
      return;
    }
    const folder = this.app.vault.getAbstractFileByPath(deckFolder);
    if (!(folder instanceof import_obsidian.TFolder)) {
      this.queue = [];
      return;
    }
    const files = this.collectMdFiles(folder);
    const now = Date.now();
    const due = [];
    for (const file of files) {
      const cardType = this.resolveCardType(file);
      const id = file.path;
      if (!this.plugin.cardData[id]) {
        this.plugin.cardData[id] = this.makeRecord(
          file.path,
          cardType,
          false,
          now
        );
      } else {
        this.plugin.cardData[id].cardType = cardType;
      }
      if (this.plugin.cardData[id].dueDate <= now) {
        due.push({
          id,
          file,
          cardType,
          isReversed: false,
          isNew: this.plugin.cardData[id].repetitions === 0
        });
      }
      if (cardType === "basic_reversed") {
        const revId = file.path + "::rev";
        if (!this.plugin.cardData[revId]) {
          this.plugin.cardData[revId] = this.makeRecord(
            file.path,
            cardType,
            true,
            now
          );
        } else {
          this.plugin.cardData[revId].cardType = cardType;
        }
        if (this.plugin.cardData[revId].dueDate <= now) {
          due.push({
            id: revId,
            file,
            cardType,
            isReversed: true,
            isNew: this.plugin.cardData[revId].repetitions === 0
          });
        }
      }
    }
    await this.plugin.persistData();
    const newCards = due.filter((c) => c.isNew).slice(0, newCardsPerDay);
    const reviews = due.filter((c) => !c.isNew).sort(
      (a, b) => this.plugin.cardData[a.id].dueDate - this.plugin.cardData[b.id].dueDate
    ).slice(0, maxReviewsPerDay);
    this.queue = [...newCards, ...reviews];
  }
  makeRecord(path, cardType, isReversed, now) {
    return {
      path,
      cardType,
      isReversed,
      repetitions: 0,
      easeFactor: DEFAULT_EASE,
      interval: 1,
      dueDate: now
    };
  }
  collectMdFiles(folder) {
    const files = [];
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        files.push(child);
      } else if (child instanceof import_obsidian.TFolder) {
        files.push(...this.collectMdFiles(child));
      }
    }
    return files;
  }
  /** Read card_type from YAML frontmatter, default to "basic". */
  resolveCardType(file) {
    var _a;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    return (fm == null ? void 0 : fm.card_type) === "basic_reversed" ? "basic_reversed" : "basic";
  }
  /** Return the front and back strings for a note. */
  async getContent(file) {
    var _a;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const raw = await this.app.vault.read(file);
    const front = (fm == null ? void 0 : fm.card_front) ? String(fm.card_front) : file.basename;
    const back = stripFrontmatter(raw);
    return { front, back };
  }
  // ── Rendering ─────────────────────────────────────────────────────────
  render() {
    const el = this.contentEl;
    el.empty();
    el.addClass("flashcard-container");
    if (!this.plugin.settings.deckFolder) {
      this.renderMessage(
        el,
        "\u2699\uFE0F No deck folder configured",
        "Open Settings \u2192 Flashcards and set the Deck Folder path."
      );
      return;
    }
    if (this.queue.length === 0) {
      this.renderMessage(
        el,
        "\u{1F389} All caught up!",
        "No cards are due for review right now."
      );
      return;
    }
    if (this.idx >= this.queue.length) {
      this.renderComplete(el);
      return;
    }
    void this.renderCard(el);
  }
  renderMessage(el, title, body) {
    const wrap = el.createDiv({ cls: "flashcard-state" });
    wrap.createEl("div", { cls: "flashcard-state-icon", text: title });
    wrap.createEl("p", { cls: "flashcard-state-body", text: body });
    const btn = wrap.createEl("button", {
      cls: "flashcard-btn flashcard-btn-primary",
      text: "Refresh"
    });
    btn.addEventListener("click", () => void this.startSession());
  }
  renderComplete(el) {
    const wrap = el.createDiv({ cls: "flashcard-state" });
    wrap.createEl("div", { cls: "flashcard-state-icon", text: "\u{1F389}" });
    wrap.createEl("h2", { cls: "flashcard-state-title", text: "Session Complete!" });
    wrap.createEl("p", {
      cls: "flashcard-state-body",
      text: `You reviewed ${this.queue.length} card(s).`
    });
    const btn = wrap.createEl("button", {
      cls: "flashcard-btn flashcard-btn-primary",
      text: "Start New Session"
    });
    btn.addEventListener("click", () => void this.startSession());
  }
  async renderCard(el) {
    const card = this.queue[this.idx];
    const rec = this.plugin.cardData[card.id];
    const { front, back } = await this.getContent(card.file);
    const header = el.createDiv({ cls: "flashcard-header" });
    const progRow = header.createDiv({ cls: "flashcard-progress-row" });
    progRow.createSpan({
      cls: "flashcard-progress-text",
      text: `${this.idx + 1} / ${this.queue.length}`
    });
    const bar = header.createDiv({ cls: "flashcard-progress-bar" });
    bar.createDiv({
      cls: "flashcard-progress-fill",
      attr: {
        style: `width:${this.idx / this.queue.length * 100}%`
      }
    });
    const meta = header.createDiv({ cls: "flashcard-meta" });
    const typeLabel = card.isReversed ? "Basic (Reversed)" : card.cardType === "basic_reversed" ? "Basic + Reversed" : "Basic";
    meta.createSpan({ cls: "flashcard-type-label", text: typeLabel });
    if (rec.repetitions === 0) {
      meta.createSpan({ cls: "flashcard-badge flashcard-badge-new", text: "New" });
    } else {
      meta.createSpan({
        cls: "flashcard-badge flashcard-badge-review",
        text: `${rec.interval}d`
      });
    }
    const cardEl = el.createDiv({ cls: "flashcard-card" });
    const frontSide = cardEl.createDiv({ cls: "flashcard-side" });
    frontSide.createDiv({
      cls: "flashcard-side-label",
      text: card.isReversed ? "Back" : "Front"
    });
    const frontContent = frontSide.createDiv({ cls: "flashcard-content" });
    await this.renderMarkdown(
      card.isReversed ? back : front,
      frontContent,
      card.file.path
    );
    if (this.revealed) {
      cardEl.createDiv({ cls: "flashcard-divider" });
      const backSide = cardEl.createDiv({ cls: "flashcard-side" });
      backSide.createDiv({
        cls: "flashcard-side-label",
        text: card.isReversed ? "Front" : "Back"
      });
      const backContent = backSide.createDiv({ cls: "flashcard-content" });
      await this.renderMarkdown(
        card.isReversed ? front : back,
        backContent,
        card.file.path
      );
    }
    const footer = el.createDiv({ cls: "flashcard-footer" });
    if (!this.revealed) {
      const showBtn = footer.createEl("button", {
        cls: "flashcard-btn flashcard-btn-show",
        text: "Show Answer"
      });
      showBtn.addEventListener("click", () => {
        this.revealed = true;
        this.render();
      });
    } else {
      const ratingBar = footer.createDiv({ cls: "flashcard-rating-bar" });
      const ratings = [
        ["Again", 0, "flashcard-btn-again"],
        ["Hard", 1, "flashcard-btn-hard"],
        ["Good", 2, "flashcard-btn-good"],
        ["Easy", 3, "flashcard-btn-easy"]
      ];
      for (const [label, rating, cls] of ratings) {
        const wrap = ratingBar.createDiv({ cls: "flashcard-rating-cell" });
        wrap.createDiv({
          cls: "flashcard-interval-label",
          text: formatInterval(rating, rec)
        });
        const btn = wrap.createEl("button", {
          cls: `flashcard-btn ${cls}`,
          text: label
        });
        btn.addEventListener("click", () => void this.submitRating(card.id, rating));
      }
    }
  }
  async renderMarkdown(markdown, el, sourcePath) {
    try {
      await import_obsidian.MarkdownRenderer.render(this.app, markdown, el, sourcePath, this);
    } catch (err) {
      console.error("Flashcards: MarkdownRenderer failed", err);
      el.createEl("pre", { text: markdown });
    }
  }
  async submitRating(cardId, rating) {
    const rec = this.plugin.cardData[cardId];
    if (rec) {
      this.plugin.cardData[cardId] = applyRating(rec, rating);
      await this.plugin.persistData();
    }
    this.idx++;
    this.revealed = false;
    this.render();
  }
};
var FlashcardsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Flashcards Settings" });
    new import_obsidian.Setting(containerEl).setName("Deck Folder").setDesc(
      'Path to the folder whose notes become flashcards (e.g. "Flashcards" or "Notes/Vocab").'
    ).addText(
      (text) => text.setPlaceholder("Flashcards").setValue(this.plugin.settings.deckFolder).onChange(async (value) => {
        this.plugin.settings.deckFolder = value.trim();
        await this.plugin.persistData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("New Cards Per Day").setDesc("Maximum number of new (unseen) cards shown per session.").addSlider(
      (slider) => slider.setLimits(1, 100, 1).setValue(this.plugin.settings.newCardsPerDay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.newCardsPerDay = value;
        await this.plugin.persistData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max Reviews Per Day").setDesc("Maximum number of due review cards shown per session.").addSlider(
      (slider) => slider.setLimits(1, 500, 1).setValue(this.plugin.settings.maxReviewsPerDay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxReviewsPerDay = value;
        await this.plugin.persistData();
      })
    );
    containerEl.createEl("h3", { text: "Card Format" });
    const desc = containerEl.createEl("p", {
      cls: "setting-item-description"
    });
    desc.textContent = "Every .md file in the deck folder is one flashcard. Use optional YAML frontmatter to customise the card:";
    const ul = containerEl.createEl("ul");
    ul.createEl("li", {
      text: 'card_front: "Question text" \u2014 overrides the filename as the front.'
    });
    ul.createEl("li", {
      text: "card_type: basic_reversed \u2014 creates two cards (Front\u2192Back and Back\u2192Front)."
    });
    containerEl.createEl("h4", { text: "Example" });
    containerEl.createEl("pre").createEl("code", {
      text: [
        "---",
        "card_type: basic_reversed",
        "card_front: What is the capital of France?",
        "---",
        "Paris"
      ].join("\n")
    });
  }
};
var FlashcardsPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    /** In-memory card records, kept in sync with data.json. */
    this.cardData = {};
  }
  async onload() {
    var _a, _b;
    const stored = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = stored == null ? void 0 : stored.settings) != null ? _a : {});
    this.cardData = (_b = stored == null ? void 0 : stored.cards) != null ? _b : {};
    this.registerView(
      VIEW_TYPE_FLASHCARD,
      (leaf) => new FlashcardView(leaf, this)
    );
    this.addRibbonIcon(
      "brain",
      "Open Flashcards",
      () => void this.openStudyView()
    );
    this.addCommand({
      id: "open-flashcard-deck",
      name: "Open Flashcard Deck",
      callback: () => void this.openStudyView()
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFolder) {
          menu.addItem(
            (item) => item.setTitle("Set as Flashcard Deck").setIcon("layers").onClick(async () => {
              this.settings.deckFolder = file.path;
              await this.persistData();
              new import_obsidian.Notice(`Flashcard deck \u2192 ${file.path}`);
            })
          );
        }
      })
    );
    this.addSettingTab(new FlashcardsSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_FLASHCARD);
  }
  /** Save both settings and card data atomically. */
  async persistData() {
    await this.saveData({
      settings: this.settings,
      cards: this.cardData
    });
  }
  /** Open (or reveal) the flashcard study panel. */
  async openStudyView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_FLASHCARD);
    if (existing.length > 0) {
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_FLASHCARD, active: true });
    workspace.revealLeaf(leaf);
  }
};
