/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository:
https://github.com/MichaelLing83/Obsidian-flashcards
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  FlashcardView: () => FlashcardView,
  default: () => FlashcardsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  newCardsPerDay: 20,
  maxReviewsPerDay: 100,
  cardFontSizePx: 22,
  deckFontSizePxByPath: {},
  aiCompleteRetryCount: 3
};
var DEFAULT_EASE = 2.5;
var MIN_EASE = 1.3;
var MS_PER_DAY = 864e5;
var DEBUG_PREFIX = "[Flashcards]";
var MIN_CARD_FONT_SIZE_PX = 14;
var MAX_CARD_FONT_SIZE_PX = 48;
var DEFAULT_OLLAMA_BASE_URL = "http://127.0.0.1:11434";
var DEFAULT_VOLCENGINE_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3";
var MIN_AI_RETRY_COUNT = 0;
var MAX_AI_RETRY_COUNT = 10;
var VIEW_TYPE_FLASHCARD = "flashcard-study-view";
var QUALITY = [1, 3, 4, 5];
function nextInterval(rating, rec) {
  const q = QUALITY[rating];
  if (q < 3) return 1;
  if (rec.repetitions === 0) return 1;
  if (rec.repetitions === 1) return 6;
  return Math.round(rec.interval * rec.easeFactor);
}
function cloneCardRecord(rec) {
  return { ...rec };
}
function applyRating(rec, rating) {
  const q = QUALITY[rating];
  const interval = nextInterval(rating, rec);
  const repetitions = q < 3 ? 0 : rec.repetitions + 1;
  let easeFactor = rec.easeFactor + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02));
  if (easeFactor < MIN_EASE) easeFactor = MIN_EASE;
  const dueDate = Date.now() + interval * MS_PER_DAY;
  return { ...rec, repetitions, easeFactor, interval, dueDate };
}
function formatInterval(rating, rec) {
  const d = nextInterval(rating, rec);
  if (d < 2) return "1d";
  if (d < 7) return `${d}d`;
  if (d < 30) return `${Math.round(d / 7)}w`;
  if (d < 365) return `${Math.round(d / 30)}mo`;
  return `${Math.round(d / 365)}y`;
}
function stripFrontmatter(raw) {
  if (!raw.startsWith("---")) return raw;
  const end = raw.indexOf("\n---", 3);
  if (end === -1) return raw;
  return raw.slice(end + 4).trim();
}
function parseTopLevelSections(markdown) {
  const sections = /* @__PURE__ */ new Map();
  const lines = stripFrontmatter(markdown).split("\n");
  let currentTitle = "";
  let buffer = [];
  for (const line of lines) {
    const h1 = line.match(/^#\s+(.+)$/);
    if (h1) {
      if (currentTitle) {
        sections.set(currentTitle, buffer.join("\n").trim());
      }
      currentTitle = h1[1].trim();
      buffer = [];
      continue;
    }
    if (currentTitle) {
      buffer.push(line);
    }
  }
  if (currentTitle) {
    sections.set(currentTitle, buffer.join("\n").trim());
  }
  return sections;
}
function normalizeSectionName(value) {
  return typeof value === "string" ? value.trim() : "";
}
function extractJsonPayload(raw) {
  const trimmed = raw.trim();
  const fullFence = trimmed.match(/^```(?:json)?\s*[\r\n]+([\s\S]*?)\r?\n```\s*$/i);
  if (fullFence) {
    return fullFence[1].trim();
  }
  const firstFence = raw.match(/```(?:json)?\s*[\r\n]+([\s\S]*?)\r?\n```/i);
  if (firstFence) {
    return firstFence[1].trim();
  }
  return trimmed;
}
function parseDeckConfig(raw) {
  let parsed;
  try {
    parsed = JSON.parse(extractJsonPayload(raw));
  } catch (e) {
    return {
      config: null,
      error: "Invalid config JSON. Use a JSON object with requiredSections and instances (raw JSON or wrapped in ```json ... ```)."
    };
  }
  if (!parsed || typeof parsed !== "object") {
    return { config: null, error: "Config must be a JSON object." };
  }
  const obj = parsed;
  if (!Array.isArray(obj.requiredSections) || obj.requiredSections.length === 0) {
    return {
      config: null,
      error: "requiredSections must be a non-empty string array."
    };
  }
  const requiredSections = obj.requiredSections.map((v) => normalizeSectionName(v)).filter((v) => v.length > 0);
  if (requiredSections.length === 0) {
    return {
      config: null,
      error: "requiredSections must contain at least one non-empty section name."
    };
  }
  if (!Array.isArray(obj.instances) || obj.instances.length === 0) {
    return {
      config: null,
      error: "instances must be a non-empty array."
    };
  }
  const requiredSet = new Set(requiredSections);
  const instances = [];
  for (const item of obj.instances) {
    let name = "";
    let promptSection = "";
    let answerSection = "";
    if (Array.isArray(item) && item.length === 2) {
      promptSection = normalizeSectionName(item[0]);
      answerSection = normalizeSectionName(item[1]);
    } else if (item && typeof item === "object") {
      const cast = item;
      name = normalizeSectionName(cast.name);
      promptSection = normalizeSectionName(cast.promptSection);
      answerSection = normalizeSectionName(cast.answerSection);
    }
    if (!promptSection || !answerSection) {
      return {
        config: null,
        error: 'Each instance must define promptSection and answerSection (or use ["A", "B"] format).'
      };
    }
    if (!requiredSet.has(promptSection) || !requiredSet.has(answerSection)) {
      return {
        config: null,
        error: `Instance (${promptSection} -> ${answerSection}) must reference sections from requiredSections.`
      };
    }
    instances.push({
      name: name || void 0,
      promptSection,
      answerSection
    });
  }
  let ai;
  if (typeof obj.ai !== "undefined") {
    if (!obj.ai || typeof obj.ai !== "object") {
      return {
        config: null,
        error: "ai must be an object when provided."
      };
    }
    const aiObj = obj.ai;
    if (aiObj.provider !== "ollama" && aiObj.provider !== "volcengine") {
      return {
        config: null,
        error: 'ai.provider must be "ollama" or "volcengine".'
      };
    }
    const model = normalizeSectionName(aiObj.model);
    if (!model) {
      return {
        config: null,
        error: "ai.model must be a non-empty string."
      };
    }
    const baseUrl = normalizeSectionName(aiObj.baseUrl) || (aiObj.provider === "volcengine" ? DEFAULT_VOLCENGINE_BASE_URL : DEFAULT_OLLAMA_BASE_URL);
    const apiKey = normalizeSectionName(aiObj.apiKey) || void 0;
    if (aiObj.provider === "volcengine" && !apiKey) {
      return {
        config: null,
        error: 'ai.apiKey must be a non-empty string when ai.provider is "volcengine".'
      };
    }
    if (!aiObj.prompts || typeof aiObj.prompts !== "object" || Array.isArray(aiObj.prompts)) {
      return {
        config: null,
        error: "ai.prompts must be an object keyed by source section and target section."
      };
    }
    const prompts = {};
    for (const [sourceRaw, targetMapRaw] of Object.entries(aiObj.prompts)) {
      const source = normalizeSectionName(sourceRaw);
      if (!requiredSet.has(source)) {
        return {
          config: null,
          error: `ai.prompts source section "${source}" must exist in requiredSections.`
        };
      }
      if (!targetMapRaw || typeof targetMapRaw !== "object" || Array.isArray(targetMapRaw)) {
        return {
          config: null,
          error: `ai.prompts.${source} must be an object keyed by target section.`
        };
      }
      const targetMap = {};
      for (const [targetRaw, promptRaw] of Object.entries(targetMapRaw)) {
        const target = normalizeSectionName(targetRaw);
        const prompt = normalizeSectionName(promptRaw);
        if (!requiredSet.has(target)) {
          return {
            config: null,
            error: `ai.prompts target section "${target}" must exist in requiredSections.`
          };
        }
        if (!prompt) {
          return {
            config: null,
            error: `ai.prompts.${source}.${target} must be a non-empty string.`
          };
        }
        targetMap[target] = prompt;
      }
      prompts[source] = targetMap;
    }
    ai = {
      provider: aiObj.provider,
      model,
      baseUrl,
      apiKey,
      prompts
    };
  }
  return {
    config: {
      requiredSections,
      instances,
      ai
    },
    error: ""
  };
}
function buildPromptFromSource(sourceContent, instruction) {
  return `${sourceContent.trim()}

${instruction.trim()}`;
}
function replaceTopLevelSectionContent(markdown, sectionName, newContent) {
  const lines = markdown.split("\n");
  const headingPattern = /^#\s+(.+)$/;
  let start = -1;
  let end = lines.length;
  for (let index = 0; index < lines.length; index++) {
    const match = lines[index].match(headingPattern);
    if (!match) continue;
    const title = match[1].trim();
    if (start === -1 && title === sectionName) {
      start = index + 1;
      continue;
    }
    if (start !== -1) {
      end = index;
      break;
    }
  }
  if (start === -1) {
    return { updatedMarkdown: markdown, updated: false };
  }
  const body = newContent.trim();
  const replacement = body ? ["", ...body.split("\n"), ""] : [""];
  const updatedLines = [
    ...lines.slice(0, start),
    ...replacement,
    ...lines.slice(end)
  ];
  return {
    updatedMarkdown: updatedLines.join("\n").replace(/\n{3,}/g, "\n\n"),
    updated: true
  };
}
var SelectionModal = class extends import_obsidian.SuggestModal {
  constructor(app, items, placeholder, toLabel, toInfo, onChoose) {
    super(app);
    this.items = items;
    this.toLabel = toLabel;
    this.toInfo = toInfo;
    this.onChoose = onChoose;
    this.setPlaceholder(placeholder);
  }
  getSuggestions(query) {
    const q = query.trim().toLowerCase();
    if (!q) return this.items;
    return this.items.filter(
      (item) => this.toLabel(item).toLowerCase().includes(q)
    );
  }
  renderSuggestion(item, el) {
    el.createDiv({ text: this.toLabel(item) });
    if (this.toInfo) {
      el.createDiv({ cls: "suggestion-note", text: this.toInfo(item) });
    }
  }
  onChooseSuggestion(item) {
    this.onChoose(item);
  }
};
var BatchCreateWizardModal = class extends import_obsidian.Modal {
  constructor(app, sections, onSubmit) {
    var _a;
    super(app);
    this.textValue = "";
    this.delimiterValue = "\\n";
    this.sections = sections;
    this.seedSection = (_a = sections[0]) != null ? _a : "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "Batch Create Flashcards" });
    contentEl.createEl("p", {
      text: "Select input section, set delimiter, then paste text to create one flashcard per segment."
    });
    contentEl.createEl("label", { text: "Input section" });
    const sectionSelect = contentEl.createEl("select");
    sectionSelect.style.width = "100%";
    for (const section of this.sections) {
      const option = sectionSelect.createEl("option", {
        text: section,
        value: section
      });
      if (section === this.seedSection) {
        option.selected = true;
      }
    }
    sectionSelect.addEventListener("change", () => {
      this.seedSection = sectionSelect.value;
    });
    contentEl.createEl("label", { text: "Delimiter" });
    contentEl.createEl("p", {
      text: "Default is \\n (one flashcard per line). You can also use custom text like --- or ;",
      cls: "setting-item-description"
    });
    const delimiterInput = contentEl.createEl("input", {
      type: "text",
      placeholder: "\\n"
    });
    delimiterInput.value = this.delimiterValue;
    delimiterInput.style.width = "100%";
    delimiterInput.addEventListener("input", () => {
      this.delimiterValue = delimiterInput.value;
    });
    contentEl.createEl("label", { text: "Input text" });
    contentEl.createEl("p", {
      text: "Paste your source text. It will be split by the delimiter and imported in batch.",
      cls: "setting-item-description"
    });
    const textArea = contentEl.createEl("textarea", {
      placeholder: "Line 1\\nLine 2\\nLine 3"
    });
    textArea.value = this.textValue;
    textArea.rows = 10;
    textArea.style.width = "100%";
    textArea.addEventListener("input", () => {
      this.textValue = textArea.value;
    });
    const footer = contentEl.createDiv({ cls: "flashcard-batch-create-actions" });
    const cancelBtn = footer.createEl("button", {
      cls: "mod-warning",
      text: "Cancel"
    });
    cancelBtn.addEventListener("click", () => this.close());
    const createBtn = footer.createEl("button", {
      cls: "mod-cta",
      text: "Create"
    });
    createBtn.addEventListener("click", () => {
      if (!this.seedSection) {
        return;
      }
      this.onSubmit({
        seedSection: this.seedSection,
        text: this.textValue,
        delimiter: this.delimiterValue
      });
      this.close();
    });
  }
};
var FlashcardView = class _FlashcardView extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.queue = [];
    this.idx = 0;
    this.revealed = false;
    this.queueBuildError = "";
    this.queueBuildErrorFilePath = "";
    this.activeSelection = null;
    /** Ratings already completed today for this instance before this session started (progress display). */
    this.dailyRatedSessionBaseline = 0;
    this.ratingUndoStack = [];
    this.ratingRedoStack = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_FLASHCARD;
  }
  getDisplayText() {
    return "Flashcards";
  }
  getIcon() {
    return "brain";
  }
  async onOpen() {
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        if (this.isActiveView() && this.canOperateOnCurrentCard()) {
          this.render();
        }
      })
    );
    await this.startSession();
  }
  isActiveView() {
    const active = this.app.workspace.getActiveViewOfType(_FlashcardView);
    return active === this;
  }
  canOperateOnCurrentCard() {
    return !this.queueBuildError && this.queue.length > 0 && this.idx < this.queue.length;
  }
  canUndoRating() {
    return this.ratingUndoStack.length > 0;
  }
  canRedoRating() {
    return this.ratingRedoStack.length > 0;
  }
  /** Whether the study view can run actions on the current queued card. */
  canStudyOperateOnCard() {
    return this.canOperateOnCurrentCard();
  }
  canStudyShowAnswer() {
    return this.canOperateOnCurrentCard() && !this.revealed;
  }
  studyShowAnswer() {
    if (!this.canStudyShowAnswer()) return;
    this.revealed = true;
    this.render();
  }
  canStudyEditCard() {
    return this.canOperateOnCurrentCard();
  }
  async studyEditCurrentCard() {
    if (!this.canStudyEditCard()) return;
    const card = this.queue[this.idx];
    await this.openCardForEditing(card.file);
  }
  canStudyCreateInDeck() {
    return !!this.activeSelection;
  }
  async studyCreateNewInDeck() {
    if (!this.canStudyCreateInDeck()) return;
    await this.createFlashcardInActiveDeck();
  }
  canStudyBatchCreateInDeck() {
    return !!this.activeSelection;
  }
  async studyBatchCreateInDeck() {
    if (!this.canStudyBatchCreateInDeck()) return;
    await this.batchCreateFlashcardsInActiveDeck();
  }
  canStudyRate() {
    return this.canOperateOnCurrentCard() && this.revealed;
  }
  async studyRate(rating) {
    if (!this.canStudyRate()) return;
    const card = this.queue[this.idx];
    await this.submitRating(card.id, rating);
  }
  async undoLastRating() {
    const entry = this.ratingUndoStack.pop();
    if (!entry) {
      new import_obsidian.Notice("Nothing to undo.");
      return;
    }
    const cur = this.plugin.cardData[entry.cardId];
    if (cur) {
      this.ratingRedoStack.push({
        cardId: entry.cardId,
        recordAfter: cloneCardRecord(cur),
        idxAfter: this.idx
      });
    }
    this.plugin.cardData[entry.cardId] = cloneCardRecord(entry.recordBefore);
    if (this.activeSelection) {
      this.plugin.recordStudyRatingUndone(this.activeSelection.instanceKey);
    }
    await this.plugin.persistData();
    this.idx = entry.idxRated;
    this.revealed = true;
    this.render();
  }
  async redoLastRating() {
    const entry = this.ratingRedoStack.pop();
    if (!entry) {
      new import_obsidian.Notice("Nothing to redo.");
      return;
    }
    const cur = this.plugin.cardData[entry.cardId];
    if (cur) {
      this.ratingUndoStack.push({
        cardId: entry.cardId,
        recordBefore: cloneCardRecord(cur),
        idxRated: this.idx
      });
    }
    this.plugin.cardData[entry.cardId] = cloneCardRecord(entry.recordAfter);
    if (this.activeSelection) {
      this.plugin.recordStudyRatingCompleted(this.activeSelection.instanceKey);
    }
    await this.plugin.persistData();
    this.idx = entry.idxAfter;
    this.revealed = false;
    this.render();
  }
  clearRatingHistoryStacks() {
    this.ratingUndoStack = [];
    this.ratingRedoStack = [];
  }
  /** (Re-)build the study queue and render the first card. */
  async startSession() {
    this.clearRatingHistoryStacks();
    this.queueBuildError = "";
    this.queueBuildErrorFilePath = "";
    this.activeSelection = null;
    const selected = await this.plugin.selectDeckInstanceForReview();
    if (selected.error) {
      this.queueBuildError = selected.error;
      this.queue = [];
      this.idx = 0;
      this.dailyRatedSessionBaseline = 0;
      this.revealed = false;
      this.render();
      return;
    }
    this.activeSelection = selected.selection;
    if (!this.activeSelection) {
      this.queueBuildError = "No deck mode selected.";
      this.queue = [];
      this.idx = 0;
      this.dailyRatedSessionBaseline = 0;
      this.revealed = false;
      this.render();
      return;
    }
    await this.buildQueue(this.activeSelection);
    this.dailyRatedSessionBaseline = this.plugin.getDailyRatedCount(
      this.activeSelection.instanceKey
    );
    this.idx = 0;
    this.revealed = false;
    this.render();
  }
  // ── Queue building ─────────────────────────────────────────────────────
  async buildQueue(selection) {
    var _a, _b, _c, _d;
    const { newCardsPerDay, maxReviewsPerDay } = this.plugin.settings;
    const files = this.collectMdFiles(selection.deck.folder);
    if (files.length === 0) {
      this.queue = [];
      return;
    }
    const now = Date.now();
    const due = [];
    for (const file of files) {
      if (this.plugin.isDeckConfigFile(file)) {
        continue;
      }
      const raw = await this.app.vault.read(file);
      const sections = parseTopLevelSections(raw);
      for (const required of selection.deck.config.requiredSections) {
        if (!sections.has(required)) {
          this.queueBuildError = `Missing required section "${required}". Every flashcard note in this deck must include all required sections.`;
          this.queueBuildErrorFilePath = file.path;
          this.queue = [];
          return;
        }
      }
      const front = (_b = (_a = sections.get(selection.instance.promptSection)) == null ? void 0 : _a.trim()) != null ? _b : "";
      const back = (_d = (_c = sections.get(selection.instance.answerSection)) == null ? void 0 : _c.trim()) != null ? _d : "";
      if (!front || !back) {
        this.queueBuildError = `Cannot build card: section "${selection.instance.promptSection}" or "${selection.instance.answerSection}" is empty.`;
        this.queueBuildErrorFilePath = file.path;
        this.queue = [];
        return;
      }
      const id = this.plugin.buildCardId(selection.instanceKey, file.path);
      if (!this.plugin.cardData[id]) {
        this.plugin.cardData[id] = this.makeRecord(file.path, now);
      }
      if (this.plugin.cardData[id].dueDate <= now) {
        due.push({
          id,
          file,
          isNew: this.plugin.cardData[id].repetitions === 0,
          front,
          back
        });
      }
    }
    await this.plugin.persistData();
    const newCards = due.filter((c) => c.isNew).slice(0, newCardsPerDay);
    const reviews = due.filter((c) => !c.isNew).sort(
      (a, b) => this.plugin.cardData[a.id].dueDate - this.plugin.cardData[b.id].dueDate
    ).slice(0, maxReviewsPerDay);
    this.queue = [...newCards, ...reviews];
  }
  makeRecord(path, now) {
    return {
      path,
      repetitions: 0,
      easeFactor: DEFAULT_EASE,
      interval: 1,
      dueDate: now
    };
  }
  collectMdFiles(folder) {
    const files = [];
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        files.push(child);
      } else if (child instanceof import_obsidian.TFolder) {
        files.push(...this.collectMdFiles(child));
      }
    }
    return files;
  }
  // ── Rendering ─────────────────────────────────────────────────────────
  render() {
    const el = this.contentEl;
    el.empty();
    el.addClass("flashcard-container");
    this.refreshFontSizeVariable();
    if (this.queueBuildError) {
      this.renderMessage(
        el,
        "\u26A0\uFE0F Deck configuration error",
        this.queueBuildError
      );
      return;
    }
    if (this.queue.length === 0) {
      this.renderMessage(
        el,
        "\u{1F389} All caught up!",
        "No cards are due for review right now."
      );
      return;
    }
    if (this.idx >= this.queue.length) {
      this.renderComplete(el);
      return;
    }
    void this.renderCard(el);
  }
  renderMessage(el, title, body) {
    const wrap = el.createDiv({ cls: "flashcard-state" });
    wrap.createEl("div", { cls: "flashcard-state-icon", text: title });
    wrap.createEl("p", { cls: "flashcard-state-body", text: body });
    if (this.queueBuildErrorFilePath) {
      const link = wrap.createEl("a", {
        cls: "flashcard-error-link",
        text: `Open note: ${this.queueBuildErrorFilePath}`
      });
      link.href = "#";
      link.addEventListener("click", (evt) => {
        evt.preventDefault();
        void this.openQueueErrorFile();
      });
    }
    if (this.activeSelection) {
      const createBtn = wrap.createEl("button", {
        cls: "flashcard-btn flashcard-btn-show",
        text: "New Flashcard"
      });
      createBtn.addEventListener(
        "click",
        () => void this.createFlashcardInActiveDeck()
      );
      const batchCreateBtn = wrap.createEl("button", {
        cls: "flashcard-btn flashcard-btn-show",
        text: "Batch Create"
      });
      batchCreateBtn.addEventListener(
        "click",
        () => void this.batchCreateFlashcardsInActiveDeck()
      );
    }
    const btn = wrap.createEl("button", {
      cls: "flashcard-btn flashcard-btn-primary",
      text: "Refresh"
    });
    btn.addEventListener("click", () => void this.startSession());
    this.renderDeckFontSizeControl(el);
    this.renderPluginVersion(wrap);
  }
  async createFlashcardInActiveDeck() {
    if (!this.activeSelection) return;
    await this.plugin.createFlashcardFromDeckFolder(this.activeSelection.deck.folder);
  }
  async batchCreateFlashcardsInActiveDeck() {
    if (!this.activeSelection) return;
    await this.plugin.batchCreateFlashcardsFromFolder(this.activeSelection.deck.folder);
  }
  async openCardForEditing(file) {
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.openFile(file);
    this.app.workspace.revealLeaf(leaf);
  }
  async openQueueErrorFile() {
    if (!this.queueBuildErrorFilePath) return;
    const target = this.app.vault.getAbstractFileByPath(this.queueBuildErrorFilePath);
    if (!(target instanceof import_obsidian.TFile)) {
      new import_obsidian.Notice(`Could not find note: ${this.queueBuildErrorFilePath}`);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.openFile(target);
    this.app.workspace.revealLeaf(leaf);
  }
  renderComplete(el) {
    const wrap = el.createDiv({ cls: "flashcard-state" });
    wrap.createEl("div", { cls: "flashcard-state-icon", text: "\u{1F389}" });
    wrap.createEl("h2", { cls: "flashcard-state-title", text: "Session Complete!" });
    wrap.createEl("p", {
      cls: "flashcard-state-body",
      text: `You reviewed ${this.queue.length} card(s).`
    });
    const btnRow = wrap.createDiv({ cls: "flashcard-complete-actions" });
    if (this.canUndoRating()) {
      const undoBtn = btnRow.createEl("button", {
        cls: "flashcard-btn flashcard-btn-secondary",
        text: "Undo last rating"
      });
      undoBtn.addEventListener("click", () => void this.undoLastRating());
    }
    const btn = btnRow.createEl("button", {
      cls: "flashcard-btn flashcard-btn-primary",
      text: "Start New Session"
    });
    btn.addEventListener("click", () => void this.startSession());
    this.renderDeckFontSizeControl(el);
    this.renderPluginVersion(wrap);
  }
  renderPluginVersion(parent) {
    parent.createDiv({
      cls: "flashcard-version",
      text: `v${this.plugin.manifest.version}`
    });
  }
  async refreshCardContentFromFile(card) {
    var _a, _b, _c, _d;
    if (!this.activeSelection) return;
    try {
      const raw = await this.app.vault.read(card.file);
      const sections = parseTopLevelSections(raw);
      card.front = (_b = (_a = sections.get(this.activeSelection.instance.promptSection)) == null ? void 0 : _a.trim()) != null ? _b : "";
      card.back = (_d = (_c = sections.get(this.activeSelection.instance.answerSection)) == null ? void 0 : _c.trim()) != null ? _d : "";
    } catch (error) {
      console.error("Flashcards: failed to refresh card content", {
        filePath: card.file.path,
        error
      });
    }
  }
  async renderCard(el) {
    const card = this.queue[this.idx];
    await this.refreshCardContentFromFile(card);
    const rec = this.plugin.cardData[card.id];
    const front = card.front;
    const back = card.back;
    const header = el.createDiv({ cls: "flashcard-header" });
    const progRow = header.createDiv({ cls: "flashcard-progress-row" });
    const typeLabel = this.activeSelection ? this.plugin.getInstanceLabel(this.activeSelection.instance) : "Deck";
    progRow.createSpan({ cls: "flashcard-type-label", text: typeLabel });
    if (rec.repetitions === 0) {
      progRow.createSpan({ cls: "flashcard-badge flashcard-badge-new", text: "New" });
    } else {
      progRow.createSpan({
        cls: "flashcard-badge flashcard-badge-review",
        text: `${rec.interval}d`
      });
    }
    const b = this.dailyRatedSessionBaseline;
    const qLen = this.queue.length;
    const progTotal = b + qLen;
    const progCur = b + this.idx + 1;
    progRow.createSpan({
      cls: "flashcard-progress-text",
      text: `${progCur} / ${progTotal}`
    });
    this.renderPluginVersion(progRow);
    const bar = header.createDiv({ cls: "flashcard-progress-bar" });
    bar.createDiv({
      cls: "flashcard-progress-fill",
      attr: {
        style: `width:${progTotal > 0 ? (b + this.idx) / progTotal * 100 : 0}%`
      }
    });
    const cardEl = el.createDiv({ cls: "flashcard-card" });
    const frontSide = cardEl.createDiv({ cls: "flashcard-side" });
    const frontContent = frontSide.createDiv({ cls: "flashcard-content" });
    await this.renderMarkdown(front, frontContent, card.file.path);
    if (this.revealed) {
      cardEl.createDiv({ cls: "flashcard-divider" });
      const backSide = cardEl.createDiv({ cls: "flashcard-side" });
      const backContent = backSide.createDiv({ cls: "flashcard-content" });
      await this.renderMarkdown(back, backContent, card.file.path);
    }
    const footer = el.createDiv({ cls: "flashcard-footer" });
    const toolbar = footer.createDiv({ cls: "flashcard-footer-toolbar" });
    const undoBtn = toolbar.createEl("button", {
      cls: "flashcard-btn flashcard-btn-secondary flashcard-btn-icon",
      attr: { "aria-label": "Undo last rating", title: "Undo last rating (\u2318/Ctrl+Z)" }
    });
    (0, import_obsidian.setIcon)(undoBtn, "undo");
    undoBtn.disabled = !this.canUndoRating();
    undoBtn.addEventListener("click", () => void this.undoLastRating());
    const redoBtn = toolbar.createEl("button", {
      cls: "flashcard-btn flashcard-btn-secondary flashcard-btn-icon",
      attr: { "aria-label": "Redo rating", title: "Redo rating (\u2318/Ctrl+Shift+Z)" }
    });
    (0, import_obsidian.setIcon)(redoBtn, "redo");
    redoBtn.disabled = !this.canRedoRating();
    redoBtn.addEventListener("click", () => void this.redoLastRating());
    const editBtn = toolbar.createEl("button", {
      cls: "flashcard-btn flashcard-btn-secondary",
      text: "Edit Card"
    });
    editBtn.addEventListener(
      "click",
      () => void this.openCardForEditing(card.file)
    );
    if (this.activeSelection) {
      const newBtn = toolbar.createEl("button", {
        cls: "flashcard-btn flashcard-btn-primary flashcard-btn-new-note",
        text: "New Flashcard"
      });
      newBtn.addEventListener(
        "click",
        () => void this.createFlashcardInActiveDeck()
      );
      const batchBtn = toolbar.createEl("button", {
        cls: "flashcard-btn flashcard-btn-show",
        text: "Batch Create"
      });
      batchBtn.addEventListener(
        "click",
        () => void this.batchCreateFlashcardsInActiveDeck()
      );
    }
    if (!this.revealed) {
      const showBtn = toolbar.createEl("button", {
        cls: "flashcard-btn flashcard-btn-show",
        text: "Show Answer"
      });
      showBtn.addEventListener("click", () => {
        this.revealed = true;
        this.render();
      });
    } else {
      const ratingBar = footer.createDiv({ cls: "flashcard-rating-bar" });
      const ratings = [
        ["Again", 0, "flashcard-btn-again"],
        ["Hard", 1, "flashcard-btn-hard"],
        ["Good", 2, "flashcard-btn-good"],
        ["Easy", 3, "flashcard-btn-easy"]
      ];
      for (const [label, rating, cls] of ratings) {
        const wrap = ratingBar.createDiv({ cls: "flashcard-rating-cell" });
        wrap.createDiv({
          cls: "flashcard-interval-label",
          text: formatInterval(rating, rec)
        });
        const btn = wrap.createEl("button", {
          cls: `flashcard-btn ${cls}`,
          text: label
        });
        btn.addEventListener("click", () => void this.submitRating(card.id, rating));
      }
    }
    this.renderDeckFontSizeControl(el);
  }
  getActiveDeckPath() {
    var _a, _b;
    return (_b = (_a = this.activeSelection) == null ? void 0 : _a.deck.folder.path) != null ? _b : null;
  }
  refreshFontSizeVariable() {
    const deckPath = this.getActiveDeckPath();
    const sizePx = this.plugin.getDeckFontSizePx(deckPath);
    this.contentEl.style.setProperty("--flashcard-font-size", `${sizePx}px`);
  }
  renderDeckFontSizeControl(parent) {
    const deckPath = this.getActiveDeckPath();
    if (!deckPath) return;
    const sizePx = this.plugin.getDeckFontSizePx(deckPath);
    const wrap = parent.createDiv({ cls: "flashcard-font-control" });
    wrap.createSpan({ cls: "flashcard-font-control-label", text: "Card Font" });
    const slider = wrap.createEl("input", {
      type: "range",
      cls: "flashcard-font-control-slider"
    });
    slider.min = String(MIN_CARD_FONT_SIZE_PX);
    slider.max = String(MAX_CARD_FONT_SIZE_PX);
    slider.step = "1";
    slider.value = String(sizePx);
    const valueLabel = wrap.createSpan({
      cls: "flashcard-font-control-value",
      text: `${sizePx}px`
    });
    slider.addEventListener("input", () => {
      const current = Number(slider.value);
      valueLabel.setText(`${current}px`);
      this.contentEl.style.setProperty("--flashcard-font-size", `${current}px`);
    });
    slider.addEventListener("change", () => {
      const current = Number(slider.value);
      void this.plugin.setDeckFontSizePx(deckPath, current);
    });
  }
  async renderMarkdown(markdown, el, sourcePath) {
    try {
      await import_obsidian.MarkdownRenderer.render(this.app, markdown, el, sourcePath, this);
    } catch (err) {
      console.error("Flashcards: MarkdownRenderer failed", err);
      el.createEl("pre", { text: markdown });
    }
  }
  async submitRating(cardId, rating) {
    const rec = this.plugin.cardData[cardId];
    const idxRated = this.idx;
    if (rec) {
      const recordBefore = cloneCardRecord(rec);
      this.plugin.cardData[cardId] = applyRating(rec, rating);
      if (this.activeSelection) {
        this.plugin.recordStudyRatingCompleted(this.activeSelection.instanceKey);
      }
      await this.plugin.persistData();
      this.ratingUndoStack.push({ cardId, recordBefore, idxRated });
      this.ratingRedoStack.length = 0;
    }
    this.idx++;
    this.revealed = false;
    this.render();
  }
};
var FlashcardsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Flashcards Settings" });
    new import_obsidian.Setting(containerEl).setName("New Cards Per Day").setDesc("Maximum number of new (unseen) cards shown per session.").addSlider(
      (slider) => slider.setLimits(1, 100, 1).setValue(this.plugin.settings.newCardsPerDay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.newCardsPerDay = value;
        await this.plugin.persistData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max Reviews Per Day").setDesc("Maximum number of due review cards shown per session.").addSlider(
      (slider) => slider.setLimits(1, 500, 1).setValue(this.plugin.settings.maxReviewsPerDay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxReviewsPerDay = value;
        await this.plugin.persistData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Card Font Size").setDesc(
      "Fallback font size for decks that don't have a deck-specific size set in the Flashcards view."
    ).addSlider(
      (slider) => slider.setLimits(MIN_CARD_FONT_SIZE_PX, MAX_CARD_FONT_SIZE_PX, 1).setValue(this.plugin.settings.cardFontSizePx).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.cardFontSizePx = value;
        this.plugin.applyCardFontSizeToOpenViews();
        await this.plugin.persistData();
      })
    );
    containerEl.createEl("h3", { text: "Study view shortcuts" });
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: 'When the Flashcards study tab is focused, you can use keyboard shortcuts for ratings and toolbar actions. Defaults include Space (show answer), E (edit current card), N (new note in deck), B (batch create for current deck), 1\u20134 (Again / Hard / Good / Easy), and Ctrl/Cmd+Z / Ctrl/Cmd+Shift+Z (undo / redo rating). While typing in a note or any text field, those shortcuts are disabled so keys like E work normally. To customize or add numpad keys, open Obsidian Settings \u2192 Hotkeys and search for "Flashcards".'
    });
    containerEl.createEl("h3", { text: "Deck Config File" });
    const desc = containerEl.createEl("p", {
      cls: "setting-item-description"
    });
    desc.textContent = "Each deck folder must contain a config file named <deck_dir>.flashcards in JSON format.";
    new import_obsidian.Setting(containerEl).setName("AI Complete Retry Count").setDesc("How many retries are allowed per flashcard when AI generation fails.").addSlider(
      (slider) => slider.setLimits(MIN_AI_RETRY_COUNT, MAX_AI_RETRY_COUNT, 1).setValue(this.plugin.settings.aiCompleteRetryCount).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.aiCompleteRetryCount = value;
        await this.plugin.persistData();
      })
    );
    const ul = containerEl.createEl("ul");
    ul.createEl("li", {
      text: "Config filename must match folder name, e.g. deck_dir/deck_dir.flashcards."
    });
    ul.createEl("li", {
      text: "requiredSections defines mandatory H1 sections in every card note."
    });
    ul.createEl("li", {
      text: "instances define prompt/answer section pairs, each becoming a study mode."
    });
    ul.createEl("li", {
      text: "Nested decks are not allowed: if a deck folder has a child deck folder, the plugin will stop and show an error."
    });
    containerEl.createEl("h4", { text: "Example" });
    containerEl.createEl("pre").createEl("code", {
      text: [
        "{",
        '  "requiredSections": ["A", "B", "C"],',
        '  "instances": [',
        '    ["A", "B"],',
        '    { "name": "B-to-C", "promptSection": "B", "answerSection": "C" }',
        "  ]",
        "}"
      ].join("\n")
    });
    containerEl.createEl("h4", { text: "Card Note Example" });
    containerEl.createEl("pre").createEl("code", {
      text: [
        "# A",
        "Prompt content",
        "",
        "# B",
        "Expected answer",
        "",
        "# C",
        "Extra context"
      ].join("\n")
    });
  }
};
var FlashcardsPlugin = class _FlashcardsPlugin extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    /** In-memory card records, kept in sync with data.json. */
    this.cardData = {};
    /** Ratings per study mode per local calendar day (persisted). */
    this.dailyRatedByInstance = {};
    this.aiStatusBarEl = null;
    this.aiDeckCompletionInProgress = false;
    this.aiDeckCompletionCancelRequested = false;
  }
  setAiStatusBarIdle() {
    if (!this.aiStatusBarEl) return;
    this.aiStatusBarEl.setText("AI Complete");
  }
  setAiStatusBarCancelling() {
    if (!this.aiStatusBarEl) return;
    this.aiStatusBarEl.setText("AI Cancelling...");
  }
  setAiStatusBarDeckProgress(processed, total) {
    if (!this.aiStatusBarEl) return;
    const safeTotal = Math.max(1, total);
    const safeProcessed = Math.max(0, Math.min(processed, safeTotal));
    const percent = Math.round(safeProcessed / safeTotal * 100);
    this.aiStatusBarEl.setText(`AI ${safeProcessed}/${safeTotal} (${percent}%)`);
  }
  logDebug(message, meta) {
    if (typeof meta === "undefined") {
      console.info(`${DEBUG_PREFIX} ${message}`);
      return;
    }
    console.info(`${DEBUG_PREFIX} ${message}`, meta);
  }
  registerDeckFolderMenuHook() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        this.logDebug("file-menu fired", {
          path: file.path,
          type: file instanceof import_obsidian.TFolder ? "folder" : "file"
        });
        this.tryAddNewFlashcardMenuItem(menu, file, "file-menu");
      })
    );
    const workspaceAny = this.app.workspace;
    this.registerEvent(
      workspaceAny.on("files-menu", (menu, files) => {
        if (!Array.isArray(files)) return;
        const first = files[0];
        const cast = first;
        this.logDebug("files-menu fired", {
          count: files.length,
          firstPath: cast == null ? void 0 : cast.path,
          firstType: cast instanceof import_obsidian.TFolder ? "folder" : "file"
        });
        if (!cast || files.length !== 1) return;
        this.tryAddNewFlashcardMenuItem(menu, cast, "files-menu");
      })
    );
  }
  registerAiCompletionUi() {
    this.aiStatusBarEl = this.addStatusBarItem();
    this.aiStatusBarEl.addClass("mod-clickable");
    this.setAiStatusBarIdle();
    this.aiStatusBarEl.addEventListener("click", () => {
      if (this.aiDeckCompletionInProgress) {
        this.aiDeckCompletionCancelRequested = true;
        this.setAiStatusBarCancelling();
        new import_obsidian.Notice("Cancelling AI deck completion after current request...");
        return;
      }
      void this.completeCurrentDeckWithAi();
    });
    this.addCommand({
      id: "ai-complete-current-flashcard",
      name: "AI Complete Current Flashcard",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        const canRun = file instanceof import_obsidian.TFile && file.extension === "md" && !this.isDeckConfigFile(file);
        if (!checking && canRun) {
          void this.completeCurrentFlashcardWithAi();
        }
        return canRun;
      }
    });
    this.addCommand({
      id: "ai-complete-current-deck",
      name: "AI Complete Current Deck",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        const canRun = file instanceof import_obsidian.TFile && file.extension === "md" && !this.isDeckConfigFile(file);
        if (!checking && canRun) {
          void this.completeCurrentDeckWithAi();
        }
        return canRun;
      }
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.updateAiStatusBarVisibility())
    );
    this.registerEvent(
      this.app.workspace.on("file-open", () => this.updateAiStatusBarVisibility())
    );
    this.updateAiStatusBarVisibility();
  }
  updateAiStatusBarVisibility() {
    if (!this.aiStatusBarEl) return;
    if (this.aiDeckCompletionInProgress) {
      this.aiStatusBarEl.style.display = "";
      return;
    }
    const activeFile = this.app.workspace.getActiveFile();
    const visible = activeFile instanceof import_obsidian.TFile && activeFile.extension === "md" && !this.isDeckConfigFile(activeFile);
    this.aiStatusBarEl.style.display = visible ? "" : "none";
  }
  tryAddNewFlashcardMenuItem(menu, file, sourceEvent) {
    var _a;
    if (!(file instanceof import_obsidian.TFolder)) {
      return;
    }
    const configFile = this.getDeckConfigFileForFolder(file);
    this.logDebug("folder context detected", {
      sourceEvent,
      folder: file.path,
      configFile: (_a = configFile == null ? void 0 : configFile.path) != null ? _a : null
    });
    const menuAny = menu;
    menuAny.addItem(
      (item) => item.setTitle("New Flashcard").setIcon("plus-circle").onClick(() => {
        var _a2;
        this.logDebug("New Flashcard clicked", {
          folder: file.path,
          configFile: (_a2 = configFile == null ? void 0 : configFile.path) != null ? _a2 : null
        });
        void this.createFlashcardFromDeckFolder(file);
      })
    );
    menuAny.addItem(
      (item) => item.setTitle("Batch Create Flashcards").setIcon("list-plus").onClick(() => {
        var _a2;
        this.logDebug("Batch Create Flashcards clicked", {
          folder: file.path,
          configFile: (_a2 = configFile == null ? void 0 : configFile.path) != null ? _a2 : null
        });
        void this.batchCreateFlashcardsFromFolder(file);
      })
    );
  }
  async onload() {
    var _a, _b, _c;
    const stored = await this.loadData();
    const merged = Object.assign({}, DEFAULT_SETTINGS, (_a = stored == null ? void 0 : stored.settings) != null ? _a : {});
    this.settings = {
      newCardsPerDay: merged.newCardsPerDay,
      maxReviewsPerDay: merged.maxReviewsPerDay,
      cardFontSizePx: Math.max(
        MIN_CARD_FONT_SIZE_PX,
        Math.min(MAX_CARD_FONT_SIZE_PX, Number(merged.cardFontSizePx) || DEFAULT_SETTINGS.cardFontSizePx)
      ),
      aiCompleteRetryCount: Math.max(
        MIN_AI_RETRY_COUNT,
        Math.min(
          MAX_AI_RETRY_COUNT,
          Number((_b = merged.aiCompleteRetryCount) != null ? _b : DEFAULT_SETTINGS.aiCompleteRetryCount)
        )
      ),
      deckFontSizePxByPath: typeof merged.deckFontSizePxByPath === "object" && merged.deckFontSizePxByPath ? Object.fromEntries(
        Object.entries(merged.deckFontSizePxByPath).map(([path, size]) => [path, Number(size)]).filter(
          ([path, size]) => typeof path === "string" && path.length > 0 && Number.isFinite(size) && size >= MIN_CARD_FONT_SIZE_PX && size <= MAX_CARD_FONT_SIZE_PX
        )
      ) : {}
    };
    this.cardData = (_c = stored == null ? void 0 : stored.cards) != null ? _c : {};
    this.dailyRatedByInstance = _FlashcardsPlugin.parseDailyRatedStored(
      stored == null ? void 0 : stored.dailyRatedByInstance
    );
    this.registerView(
      VIEW_TYPE_FLASHCARD,
      (leaf) => new FlashcardView(leaf, this)
    );
    this.addRibbonIcon(
      "brain",
      "Open Flashcards",
      () => void this.openStudyView()
    );
    this.addCommand({
      id: "open-flashcard-deck",
      name: "Open Flashcard Deck",
      callback: () => void this.openStudyView()
    });
    this.addCommand({
      id: "batch-create-flashcards",
      name: "Batch Create Flashcards",
      callback: () => void this.batchCreateFlashcards()
    });
    this.addCommand({
      id: "flashcards-undo-rating",
      name: "Flashcards: Undo last rating",
      hotkeys: [{ modifiers: ["Mod"], key: "z" }],
      checkCallback: (checking) => {
        if (this.shouldDeferFlashcardStudyHotkeys()) return false;
        const view = this.getFlashcardView();
        const ok = !!(view == null ? void 0 : view.canUndoRating());
        if (!checking && ok) void view.undoLastRating();
        return ok;
      }
    });
    this.addCommand({
      id: "flashcards-redo-rating",
      name: "Flashcards: Redo rating",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "z" }],
      checkCallback: (checking) => {
        if (this.shouldDeferFlashcardStudyHotkeys()) return false;
        const view = this.getFlashcardView();
        const ok = !!(view == null ? void 0 : view.canRedoRating());
        if (!checking && ok) void view.redoLastRating();
        return ok;
      }
    });
    this.registerFlashcardStudyCommands();
    this.logDebug("plugin loaded", { version: this.manifest.version });
    this.registerDeckFolderMenuHook();
    this.registerAiCompletionUi();
    this.applyCardFontSizeToOpenViews();
    this.addSettingTab(new FlashcardsSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_FLASHCARD);
  }
  /** Save both settings and card data atomically. */
  async persistData() {
    await this.saveData({
      settings: this.settings,
      cards: this.cardData,
      dailyRatedByInstance: this.dailyRatedByInstance
    });
  }
  /** Local calendar date YYYY-MM-DD for daily study counters. */
  localDateKey() {
    const d = /* @__PURE__ */ new Date();
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  }
  /** How many cards were rated today in this study mode (instanceKey). */
  getDailyRatedCount(instanceKey) {
    const e = this.dailyRatedByInstance[instanceKey];
    if (!e || e.date !== this.localDateKey()) return 0;
    return Math.max(0, Math.floor(Number(e.count)) || 0);
  }
  recordStudyRatingCompleted(instanceKey) {
    const date = this.localDateKey();
    const cur = this.dailyRatedByInstance[instanceKey];
    const base = (cur == null ? void 0 : cur.date) === date ? Math.max(0, Math.floor(Number(cur.count)) || 0) : 0;
    this.dailyRatedByInstance[instanceKey] = { date, count: base + 1 };
  }
  recordStudyRatingUndone(instanceKey) {
    const date = this.localDateKey();
    const cur = this.dailyRatedByInstance[instanceKey];
    const base = (cur == null ? void 0 : cur.date) === date ? Math.max(0, Math.floor(Number(cur.count)) || 0) : 0;
    this.dailyRatedByInstance[instanceKey] = { date, count: Math.max(0, base - 1) };
  }
  static parseDailyRatedStored(raw) {
    const out = {};
    if (!raw || typeof raw !== "object") return out;
    for (const [k, v] of Object.entries(raw)) {
      if (typeof k !== "string" || !v || typeof v !== "object") continue;
      const date = v.date;
      const count = v.count;
      if (typeof date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(date) && typeof count === "number" && Number.isFinite(count)) {
        out[k] = { date, count: Math.max(0, Math.floor(count)) };
      }
    }
    return out;
  }
  /** Open (or reveal) the flashcard study panel. */
  async openStudyView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_FLASHCARD);
    if (existing.length > 0) {
      this.applyCardFontSizeToOpenViews();
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_FLASHCARD, active: true });
    this.applyCardFontSizeToOpenViews();
    workspace.revealLeaf(leaf);
  }
  /** Flashcards study view in the active leaf, if any (for commands). */
  getFlashcardView() {
    return this.app.workspace.getActiveViewOfType(FlashcardView);
  }
  /**
   * When focus is in a note editor or any text field, skip flashcard hotkeys so
   * bare keys (e.g. "e") reach the editor. Obsidian evaluates plugin commands
   * globally, so this avoids stealing typing hotkeys.
   */
  shouldDeferFlashcardStudyHotkeys() {
    var _a;
    const ws = this.app.workspace;
    if ((_a = ws.activeEditor) == null ? void 0 : _a.editor) return true;
    if (ws.getActiveViewOfType(import_obsidian.MarkdownView)) return true;
    const el = document.activeElement;
    if (!(el instanceof HTMLElement)) return false;
    if (el.isContentEditable) return true;
    const tag = el.tagName;
    return tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT";
  }
  /**
   * Study-view actions with default hotkeys. Users can change bindings in
   * Obsidian Settings → Hotkeys (search "Flashcards").
   */
  registerFlashcardStudyCommands() {
    const runStudy = (checking, enabled, exec) => {
      if (this.shouldDeferFlashcardStudyHotkeys()) return false;
      const view = this.getFlashcardView();
      if (!view) return false;
      if (!enabled(view)) return false;
      if (!checking) void exec(view);
      return true;
    };
    this.addCommand({
      id: "flashcards-study-show-answer",
      name: "Flashcards: Show answer (study view)",
      hotkeys: [{ modifiers: [], key: " " }],
      checkCallback: (checking) => runStudy(
        checking,
        (v) => v.canStudyShowAnswer(),
        (v) => v.studyShowAnswer()
      )
    });
    this.addCommand({
      id: "flashcards-study-edit-card",
      name: "Flashcards: Edit current card (study view)",
      hotkeys: [{ modifiers: [], key: "e" }],
      checkCallback: (checking) => runStudy(
        checking,
        (v) => v.canStudyEditCard(),
        (v) => void v.studyEditCurrentCard()
      )
    });
    this.addCommand({
      id: "flashcards-study-new-note",
      name: "Flashcards: New flashcard in current deck (study view)",
      hotkeys: [{ modifiers: [], key: "n" }],
      checkCallback: (checking) => runStudy(
        checking,
        (v) => v.canStudyCreateInDeck(),
        (v) => void v.studyCreateNewInDeck()
      )
    });
    this.addCommand({
      id: "flashcards-study-batch-current-deck",
      name: "Flashcards: Batch create for current deck (study view)",
      hotkeys: [{ modifiers: [], key: "b" }],
      checkCallback: (checking) => runStudy(
        checking,
        (v) => v.canStudyBatchCreateInDeck(),
        (v) => void v.studyBatchCreateInDeck()
      )
    });
    const rate = (id, name, key, rating) => this.addCommand({
      id,
      name,
      hotkeys: [{ modifiers: [], key }],
      checkCallback: (checking) => runStudy(
        checking,
        (v) => v.canStudyRate(),
        (v) => void v.studyRate(rating)
      )
    });
    rate("flashcards-study-rate-again", "Flashcards: Rate Again (study view)", "1", 0);
    rate("flashcards-study-rate-hard", "Flashcards: Rate Hard (study view)", "2", 1);
    rate("flashcards-study-rate-good", "Flashcards: Rate Good (study view)", "3", 2);
    rate("flashcards-study-rate-easy", "Flashcards: Rate Easy (study view)", "4", 3);
  }
  applyCardFontSizeToOpenViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_FLASHCARD)) {
      const view = leaf.view;
      if (view instanceof FlashcardView) {
        view.refreshFontSizeVariable();
      }
    }
  }
  async getDeckDefinitionForNote(file) {
    if (this.isDeckConfigFile(file)) {
      return {
        deck: null,
        error: "Deck config files cannot be AI-completed as flashcard notes."
      };
    }
    const discovered = await this.discoverDeckDefinitions();
    if (discovered.error) {
      return { deck: null, error: discovered.error };
    }
    const deck = discovered.decks.filter((candidate) => file.path.startsWith(`${candidate.folder.path}/`)).sort((a, b) => b.folder.path.length - a.folder.path.length)[0];
    if (!deck) {
      return {
        deck: null,
        error: `The active note is not inside a configured flashcards deck: ${file.path}`
      };
    }
    return { deck, error: "" };
  }
  async generateWithOllama(ai, prompt) {
    const baseUrl = (ai.baseUrl || DEFAULT_OLLAMA_BASE_URL).replace(/\/$/, "");
    const response = await fetch(`${baseUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: ai.model,
        prompt,
        stream: false
      })
    });
    if (!response.ok) {
      throw new Error(`Ollama request failed with status ${response.status}`);
    }
    const payload = await response.json();
    const output = typeof payload.response === "string" ? payload.response.trim() : "";
    if (!output) {
      throw new Error("Ollama returned empty content.");
    }
    return output;
  }
  async generateWithVolcEngine(ai, prompt) {
    var _a, _b, _c;
    const baseUrl = (ai.baseUrl || DEFAULT_VOLCENGINE_BASE_URL).replace(/\/$/, "");
    if (!ai.apiKey) {
      throw new Error("VolcEngine API key is missing.");
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: `${baseUrl}/chat/completions`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ai.apiKey}`
      },
      body: JSON.stringify({
        model: ai.model,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      })
    });
    if (response.status < 200 || response.status >= 300) {
      const errorText = typeof response.text === "string" ? response.text : "";
      throw new Error(
        `VolcEngine request failed with status ${response.status}${errorText ? `: ${errorText}` : ""}`
      );
    }
    const payload = response.json;
    const output = typeof ((_c = (_b = (_a = payload.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) === "string" ? payload.choices[0].message.content.trim() : "";
    if (!output) {
      throw new Error("VolcEngine returned empty content.");
    }
    return output;
  }
  async generateAiOutput(ai, prompt) {
    this.logDebug("AI request start", {
      provider: ai.provider,
      model: ai.model,
      baseUrl: ai.baseUrl,
      promptLength: prompt.length
    });
    switch (ai.provider) {
      case "ollama":
        return this.generateWithOllama(ai, prompt);
      case "volcengine":
        return this.generateWithVolcEngine(ai, prompt);
      default:
        throw new Error(`Unsupported AI provider: ${ai.provider}`);
    }
  }
  findAiCompletionPlan(deck, sections) {
    var _a, _b, _c, _d, _e;
    if (!deck.config.ai) {
      return { error: `Deck ${deck.folder.path} has no ai configuration.` };
    }
    let sourceSection = "";
    let sourceContent = "";
    for (const section of deck.config.requiredSections) {
      const content = (_b = (_a = sections.get(section)) == null ? void 0 : _a.trim()) != null ? _b : "";
      if (content) {
        sourceSection = section;
        sourceContent = content;
        break;
      }
    }
    if (!sourceSection) {
      return { error: "No source section has content yet. Fill the first source section before using AI Complete." };
    }
    const targetPrompts = deck.config.ai.prompts[sourceSection];
    if (!targetPrompts) {
      return {
        error: `No AI prompt mapping is configured from section "${sourceSection}".`
      };
    }
    for (const targetSection of deck.config.requiredSections) {
      if (targetSection === sourceSection) continue;
      const targetContent = (_d = (_c = sections.get(targetSection)) == null ? void 0 : _c.trim()) != null ? _d : "";
      if (targetContent) continue;
      const instruction = (_e = targetPrompts[targetSection]) == null ? void 0 : _e.trim();
      if (instruction) {
        return {
          sourceSection,
          sourceContent,
          targetSection,
          instruction,
          aI: deck.config.ai
        };
      }
    }
    return {
      error: `No AI prompt mapping found from section "${sourceSection}" to an empty target section.`
    };
  }
  logAiPlan(filePath, sourceSection, targetSection) {
    this.logDebug("AI completion plan", {
      filePath,
      sourceSection,
      targetSection
    });
  }
  async prepareAiCompletionTask(file, deck) {
    const raw = await this.app.vault.read(file);
    const sections = parseTopLevelSections(raw);
    const plan = this.findAiCompletionPlan(deck, sections);
    if ("error" in plan) {
      return null;
    }
    return {
      file,
      raw,
      plan
    };
  }
  async executeAiCompletionTask(task) {
    var _a, _b;
    this.logDebug("AI single start", {
      filePath: task.file.path,
      deckPath: (_b = (_a = task.file.parent) == null ? void 0 : _a.path) != null ? _b : "",
      retryCount: this.settings.aiCompleteRetryCount
    });
    this.logAiPlan(task.file.path, task.plan.sourceSection, task.plan.targetSection);
    const prompt = buildPromptFromSource(task.plan.sourceContent, task.plan.instruction);
    const maxAttempts = this.settings.aiCompleteRetryCount + 1;
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        const output = await this.generateAiOutput(task.plan.aI, prompt);
        const updated = replaceTopLevelSectionContent(task.raw, task.plan.targetSection, output);
        if (!updated.updated) {
          this.logDebug("AI single failed: target section not found", {
            filePath: task.file.path,
            targetSection: task.plan.targetSection
          });
          return "failed";
        }
        await this.app.vault.modify(task.file, updated.updatedMarkdown);
        this.logDebug("AI single filled", {
          filePath: task.file.path,
          targetSection: task.plan.targetSection,
          outputLength: output.length,
          attempt
        });
        return "filled";
      } catch (error) {
        if (attempt < maxAttempts) {
          this.logDebug("AI single retry", {
            filePath: task.file.path,
            attempt,
            nextAttempt: attempt + 1,
            error: error instanceof Error ? error.message : String(error)
          });
          continue;
        }
        console.error(`${DEBUG_PREFIX} AI completion failed`, {
          file: task.file.path,
          attempt,
          maxAttempts,
          error
        });
        return "failed";
      }
    }
    return "failed";
  }
  async completeSingleFlashcardWithAi(file, deck) {
    const task = await this.prepareAiCompletionTask(file, deck);
    if (!task) {
      return "skipped";
    }
    return this.executeAiCompletionTask(task);
  }
  async completeCurrentFlashcardWithAi() {
    const file = this.app.workspace.getActiveFile();
    if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") {
      new import_obsidian.Notice("Open a markdown flashcard note before using AI Complete.");
      return;
    }
    const deckResult = await this.getDeckDefinitionForNote(file);
    if (!deckResult.deck) {
      new import_obsidian.Notice(deckResult.error);
      return;
    }
    this.logDebug("AI current note command", {
      filePath: file.path,
      deckPath: deckResult.deck.folder.path
    });
    new import_obsidian.Notice("AI completing current flashcard...");
    const status = await this.completeSingleFlashcardWithAi(file, deckResult.deck);
    if (status === "filled") {
      new import_obsidian.Notice("Filled one section with AI output.");
    } else if (status === "skipped") {
      new import_obsidian.Notice("No eligible empty target section found for current flashcard.");
    } else {
      new import_obsidian.Notice("AI completion failed for current flashcard.");
    }
  }
  async completeCurrentDeckWithAi() {
    if (this.aiDeckCompletionInProgress) {
      this.aiDeckCompletionCancelRequested = true;
      this.setAiStatusBarCancelling();
      new import_obsidian.Notice("Cancelling AI deck completion after current request...");
      return;
    }
    const active = this.app.workspace.getActiveFile();
    if (!(active instanceof import_obsidian.TFile) || active.extension !== "md") {
      new import_obsidian.Notice("Open a flashcard note inside the deck first.");
      return;
    }
    const deckResult = await this.getDeckDefinitionForNote(active);
    if (!deckResult.deck) {
      new import_obsidian.Notice(deckResult.error);
      return;
    }
    this.logDebug("AI deck command", {
      activeFile: active.path,
      deckPath: deckResult.deck.folder.path
    });
    const files = this.collectDeckMarkdownFiles(deckResult.deck.folder);
    if (files.length === 0) {
      new import_obsidian.Notice("No flashcard notes found in this deck.");
      return;
    }
    const tasks = [];
    for (const file of files) {
      const task = await this.prepareAiCompletionTask(file, deckResult.deck);
      if (task) {
        tasks.push(task);
      }
    }
    if (tasks.length === 0) {
      new import_obsidian.Notice("No eligible flashcards need AI completion in this deck.");
      return;
    }
    this.aiDeckCompletionInProgress = true;
    this.aiDeckCompletionCancelRequested = false;
    this.setAiStatusBarDeckProgress(0, tasks.length);
    this.updateAiStatusBarVisibility();
    try {
      new import_obsidian.Notice(`AI completing deck: ${deckResult.deck.folder.path} (${tasks.length} eligible notes)...`);
      let filled = 0;
      let failed = 0;
      let processed = 0;
      let cancelled = false;
      for (let index = 0; index < tasks.length; index++) {
        if (this.aiDeckCompletionCancelRequested) {
          cancelled = true;
          break;
        }
        const status = await this.executeAiCompletionTask(tasks[index]);
        if (status === "filled") filled++;
        else failed++;
        processed++;
        this.setAiStatusBarDeckProgress(processed, tasks.length);
        if (this.aiDeckCompletionCancelRequested) {
          cancelled = true;
          break;
        }
      }
      this.logDebug("AI deck command done", {
        deckPath: deckResult.deck.folder.path,
        totalEligible: tasks.length,
        processed,
        filled,
        failed,
        cancelled
      });
      if (cancelled) {
        new import_obsidian.Notice(
          `AI deck completion cancelled: processed ${processed}/${tasks.length}, filled ${filled}, failed ${failed}.`,
          8e3
        );
      } else {
        new import_obsidian.Notice(
          `AI deck completion done: processed ${processed}, filled ${filled}, failed ${failed}.`,
          8e3
        );
      }
    } finally {
      this.aiDeckCompletionInProgress = false;
      this.aiDeckCompletionCancelRequested = false;
      this.setAiStatusBarIdle();
      this.updateAiStatusBarVisibility();
    }
  }
  getDeckFontSizePx(deckPath) {
    var _a;
    if (!deckPath) return this.settings.cardFontSizePx;
    return (_a = this.settings.deckFontSizePxByPath[deckPath]) != null ? _a : this.settings.cardFontSizePx;
  }
  async setDeckFontSizePx(deckPath, sizePx) {
    const clamped = Math.max(
      MIN_CARD_FONT_SIZE_PX,
      Math.min(MAX_CARD_FONT_SIZE_PX, Math.round(sizePx))
    );
    this.settings.deckFontSizePxByPath[deckPath] = clamped;
    this.applyCardFontSizeToOpenViews();
    await this.persistData();
  }
  buildCardId(instanceKey, notePath) {
    return `${instanceKey}::${notePath}`;
  }
  isDescendantFolder(parentPath, childPath) {
    if (parentPath === childPath) return false;
    if (parentPath === "") return childPath !== "";
    return childPath.startsWith(`${parentPath}/`);
  }
  getInstanceLabel(instance) {
    return instance.name || `${instance.promptSection} -> ${instance.answerSection}`;
  }
  getInstanceKey(deckPath, instance) {
    return `${deckPath}::${instance.promptSection}->${instance.answerSection}`;
  }
  isDeckConfigFileName(fileName, folderName) {
    const lowerName = fileName.toLowerCase();
    const lowerFolder = folderName.toLowerCase();
    return lowerName === `${lowerFolder}.flashcards` || lowerName === `${lowerFolder}.flashcards.md`;
  }
  isDeckConfigFile(file) {
    if (!file.parent) return false;
    return this.isDeckConfigFileName(file.name, file.parent.name);
  }
  getDeckConfigFileForFolder(folder) {
    for (const child of folder.children) {
      if (!(child instanceof import_obsidian.TFile)) continue;
      if (this.isDeckConfigFileName(child.name, folder.name)) {
        return child;
      }
    }
    return null;
  }
  async getDeckDefinitionForFolder(folder) {
    const configFile = this.getDeckConfigFileForFolder(folder);
    if (!configFile) {
      return {
        deck: null,
        error: `Missing config file ${folder.name}.flashcards in ${folder.path}`
      };
    }
    const raw = await this.app.vault.read(configFile);
    const parsed = parseDeckConfig(raw);
    if (!parsed.config) {
      return {
        deck: null,
        error: `Config error in ${configFile.path}: ${parsed.error}`
      };
    }
    return {
      deck: {
        folder,
        configFile,
        config: parsed.config
      },
      error: ""
    };
  }
  createFlashcardTemplate(requiredSections) {
    return requiredSections.map((section) => `# ${section}
`).join("\n");
  }
  createFlashcardTemplateWithSeedContent(requiredSections, seedSection, seedContent) {
    const normalizedSeed = seedContent.trim();
    return requiredSections.map((section) => {
      if (section !== seedSection) {
        return `# ${section}
`;
      }
      if (!normalizedSeed) {
        return `# ${section}
`;
      }
      return `# ${section}
${normalizedSeed}
`;
    }).join("\n");
  }
  normalizeBatchDelimiter(raw) {
    const trimmed = raw.trim();
    if (!trimmed) return "\n";
    return trimmed.replace(/\\r/g, "\r").replace(/\\n/g, "\n").replace(/\\t/g, "	");
  }
  splitBatchSeedText(rawText, delimiterRaw) {
    const delimiter = this.normalizeBatchDelimiter(delimiterRaw);
    const chunks = delimiter === "\n" ? rawText.split(/\r?\n/g) : rawText.split(delimiter);
    return chunks.map((chunk) => chunk.trim()).filter((chunk) => chunk.length > 0);
  }
  async promptBatchCreateWizardInput(requiredSections) {
    return await new Promise((resolve) => {
      let settled = false;
      const modal = new BatchCreateWizardModal(this.app, requiredSections, (result) => {
        settled = true;
        this.logDebug("Batch create wizard submitted", {
          seedSection: result.seedSection,
          textLength: result.text.length,
          delimiter: result.delimiter
        });
        resolve(result);
      });
      const close = modal.onClose.bind(modal);
      modal.onClose = () => {
        close();
        if (!settled) {
          this.logDebug("Batch create wizard modal closed without submit", {
            requiredSections
          });
          resolve(null);
        }
      };
      window.setTimeout(() => modal.open(), 0);
    });
  }
  async batchCreateFlashcardsFromDeck(deck, seedSection, seedChunks) {
    let created = 0;
    let failed = 0;
    let firstCreatedPath = "";
    for (const chunk of seedChunks) {
      const notePath = this.getUniqueNewFlashcardPath(deck.folder);
      const content = this.createFlashcardTemplateWithSeedContent(
        deck.config.requiredSections,
        seedSection,
        chunk
      );
      try {
        const createdFile = await this.app.vault.create(notePath, content);
        created++;
        if (!firstCreatedPath) {
          firstCreatedPath = createdFile.path;
        }
      } catch (error) {
        failed++;
        console.error(`${DEBUG_PREFIX} batch create failed`, {
          notePath,
          error
        });
      }
    }
    return { created, failed, firstCreatedPath };
  }
  async runBatchCreateWizard(deck) {
    this.logDebug("Batch create wizard start", {
      deckPath: deck.folder.path,
      requiredSections: deck.config.requiredSections
    });
    const input = await this.promptBatchCreateWizardInput(deck.config.requiredSections);
    if (!input) {
      new import_obsidian.Notice("Batch creation cancelled.");
      return;
    }
    const chunks = this.splitBatchSeedText(input.text, input.delimiter);
    if (chunks.length === 0) {
      new import_obsidian.Notice("No valid input found. Please provide text that can be split into entries.");
      return;
    }
    new import_obsidian.Notice(`Creating ${chunks.length} flashcard(s) in ${deck.folder.path}...`);
    const result = await this.batchCreateFlashcardsFromDeck(deck, input.seedSection, chunks);
    if (result.firstCreatedPath) {
      const firstFile = this.app.vault.getAbstractFileByPath(result.firstCreatedPath);
      if (firstFile instanceof import_obsidian.TFile) {
        const leaf = this.app.workspace.getLeaf("tab");
        await leaf.openFile(firstFile);
      }
    }
    new import_obsidian.Notice(
      `Batch create done: created ${result.created}, failed ${result.failed}.`,
      8e3
    );
  }
  async batchCreateFlashcardsFromFolder(folder) {
    const deckResult = await this.getDeckDefinitionForFolder(folder);
    if (!deckResult.deck) {
      new import_obsidian.Notice(deckResult.error);
      return;
    }
    this.logDebug("Batch create command (folder)", {
      deckPath: folder.path
    });
    await this.runBatchCreateWizard(deckResult.deck);
  }
  async batchCreateFlashcards() {
    const discovered = await this.discoverDeckDefinitions();
    if (discovered.error) {
      new import_obsidian.Notice(discovered.error);
      return;
    }
    const deck = await this.pickOne(
      discovered.decks,
      "Select deck for batch create",
      (item) => item.folder.path,
      (item) => item.configFile.name
    );
    if (!deck) {
      new import_obsidian.Notice("Batch creation cancelled.");
      return;
    }
    this.logDebug("Batch create command", {
      deckPath: deck.folder.path
    });
    await this.runBatchCreateWizard(deck);
  }
  collectDeckMarkdownFiles(folder) {
    const files = [];
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        if (!this.isDeckConfigFile(child)) {
          files.push(child);
        }
      } else if (child instanceof import_obsidian.TFolder) {
        files.push(...this.collectDeckMarkdownFiles(child));
      }
    }
    return files;
  }
  buildDefaultFlashcardBaseName(folder) {
    const existingCount = this.collectDeckMarkdownFiles(folder).length;
    const nextIndex = existingCount + 1;
    return `${folder.name}.${String(nextIndex).padStart(4, "0")}`;
  }
  getUniqueNewFlashcardPath(folder) {
    const baseName = this.buildDefaultFlashcardBaseName(folder);
    const base = `${folder.path}/${baseName}`;
    let candidate = `${base}.md`;
    let n = Number(baseName.split(".").pop() || "1");
    while (this.app.vault.getAbstractFileByPath(candidate)) {
      n++;
      candidate = `${folder.path}/${folder.name}.${String(n).padStart(4, "0")}.md`;
    }
    return candidate;
  }
  async createFlashcardFromDeckFolder(folder) {
    const deckResult = await this.getDeckDefinitionForFolder(folder);
    if (!deckResult.deck) {
      new import_obsidian.Notice(deckResult.error);
      return;
    }
    const notePath = this.getUniqueNewFlashcardPath(folder);
    const content = this.createFlashcardTemplate(
      deckResult.deck.config.requiredSections
    );
    try {
      const created = await this.app.vault.create(notePath, content);
      const leaf = this.app.workspace.getLeaf("tab");
      await leaf.openFile(created);
      new import_obsidian.Notice(`Created flashcard: ${created.path}`);
    } catch (error) {
      console.error("Flashcards: failed to create note", error);
      new import_obsidian.Notice("Failed to create flashcard note.");
    }
  }
  async discoverDeckDefinitions() {
    const configFiles = this.app.vault.getFiles().filter((f) => this.isDeckConfigFile(f));
    if (configFiles.length === 0) {
      return {
        decks: [],
        error: "No deck config found. Add <deck_dir>.flashcards in your deck folder."
      };
    }
    const decks = [];
    for (const configFile of configFiles) {
      if (!(configFile.parent instanceof import_obsidian.TFolder)) continue;
      const raw = await this.app.vault.read(configFile);
      const parsed = parseDeckConfig(raw);
      if (!parsed.config) {
        return {
          decks: [],
          error: `Config error in ${configFile.path}: ${parsed.error}`
        };
      }
      decks.push({
        folder: configFile.parent,
        configFile,
        config: parsed.config
      });
    }
    decks.sort((a, b) => a.folder.path.length - b.folder.path.length);
    for (let i = 0; i < decks.length; i++) {
      for (let j = i + 1; j < decks.length; j++) {
        if (this.isDescendantFolder(decks[i].folder.path, decks[j].folder.path)) {
          return {
            decks: [],
            error: `Nested deck folders are not allowed: "${decks[i].folder.path}" contains child deck "${decks[j].folder.path}".`
          };
        }
      }
    }
    return { decks, error: "" };
  }
  async pickOne(items, placeholder, toLabel, toInfo) {
    if (items.length === 0) return null;
    if (items.length === 1) return items[0];
    return await new Promise((resolve) => {
      let resolved = false;
      const modal = new SelectionModal(
        this.app,
        items,
        placeholder,
        toLabel,
        toInfo,
        (item) => {
          resolved = true;
          resolve(item);
        }
      );
      const close = modal.onClose.bind(modal);
      modal.onClose = () => {
        close();
        if (!resolved) resolve(null);
      };
      modal.open();
    });
  }
  async selectDeckInstanceForReview() {
    const discovered = await this.discoverDeckDefinitions();
    if (discovered.error) {
      return { selection: null, error: discovered.error };
    }
    const deck = await this.pickOne(
      discovered.decks,
      "Select a deck folder",
      (item) => item.folder.path,
      (item) => item.configFile.name
    );
    if (!deck) {
      return { selection: null, error: "Deck selection cancelled." };
    }
    const instance = await this.pickOne(
      deck.config.instances,
      "Select a deck mode",
      (item) => this.getInstanceLabel(item),
      (item) => `${item.promptSection} -> ${item.answerSection}`
    );
    if (!instance) {
      return { selection: null, error: "Deck mode selection cancelled." };
    }
    return {
      selection: {
        deck,
        instance,
        instanceKey: this.getInstanceKey(deck.folder.path, instance)
      },
      error: ""
    };
  }
};
