/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository:
https://github.com/MichaelLing83/Obsidian-flashcards
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  FlashcardView: () => FlashcardView,
  default: () => FlashcardsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  newCardsPerDay: 20,
  maxReviewsPerDay: 100,
  cardFontSizePx: 22,
  deckFontSizePxByPath: {}
};
var DEFAULT_EASE = 2.5;
var MIN_EASE = 1.3;
var MS_PER_DAY = 864e5;
var DEBUG_PREFIX = "[Flashcards]";
var MIN_CARD_FONT_SIZE_PX = 14;
var MAX_CARD_FONT_SIZE_PX = 48;
var DEFAULT_OLLAMA_BASE_URL = "http://127.0.0.1:11434";
var DEFAULT_VOLCENGINE_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3";
var VIEW_TYPE_FLASHCARD = "flashcard-study-view";
var QUALITY = [1, 3, 4, 5];
function nextInterval(rating, rec) {
  const q = QUALITY[rating];
  if (q < 3) return 1;
  if (rec.repetitions === 0) return 1;
  if (rec.repetitions === 1) return 6;
  return Math.round(rec.interval * rec.easeFactor);
}
function applyRating(rec, rating) {
  const q = QUALITY[rating];
  const interval = nextInterval(rating, rec);
  const repetitions = q < 3 ? 0 : rec.repetitions + 1;
  let easeFactor = rec.easeFactor + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02));
  if (easeFactor < MIN_EASE) easeFactor = MIN_EASE;
  const dueDate = Date.now() + interval * MS_PER_DAY;
  return { ...rec, repetitions, easeFactor, interval, dueDate };
}
function formatInterval(rating, rec) {
  const d = nextInterval(rating, rec);
  if (d < 2) return "1d";
  if (d < 7) return `${d}d`;
  if (d < 30) return `${Math.round(d / 7)}w`;
  if (d < 365) return `${Math.round(d / 30)}mo`;
  return `${Math.round(d / 365)}y`;
}
function stripFrontmatter(raw) {
  if (!raw.startsWith("---")) return raw;
  const end = raw.indexOf("\n---", 3);
  if (end === -1) return raw;
  return raw.slice(end + 4).trim();
}
function parseTopLevelSections(markdown) {
  const sections = /* @__PURE__ */ new Map();
  const lines = stripFrontmatter(markdown).split("\n");
  let currentTitle = "";
  let buffer = [];
  for (const line of lines) {
    const h1 = line.match(/^#\s+(.+)$/);
    if (h1) {
      if (currentTitle) {
        sections.set(currentTitle, buffer.join("\n").trim());
      }
      currentTitle = h1[1].trim();
      buffer = [];
      continue;
    }
    if (currentTitle) {
      buffer.push(line);
    }
  }
  if (currentTitle) {
    sections.set(currentTitle, buffer.join("\n").trim());
  }
  return sections;
}
function normalizeSectionName(value) {
  return typeof value === "string" ? value.trim() : "";
}
function extractJsonPayload(raw) {
  const trimmed = raw.trim();
  const fullFence = trimmed.match(/^```(?:json)?\s*[\r\n]+([\s\S]*?)\r?\n```\s*$/i);
  if (fullFence) {
    return fullFence[1].trim();
  }
  const firstFence = raw.match(/```(?:json)?\s*[\r\n]+([\s\S]*?)\r?\n```/i);
  if (firstFence) {
    return firstFence[1].trim();
  }
  return trimmed;
}
function parseDeckConfig(raw) {
  let parsed;
  try {
    parsed = JSON.parse(extractJsonPayload(raw));
  } catch (e) {
    return {
      config: null,
      error: "Invalid config JSON. Use a JSON object with requiredSections and instances (raw JSON or wrapped in ```json ... ```)."
    };
  }
  if (!parsed || typeof parsed !== "object") {
    return { config: null, error: "Config must be a JSON object." };
  }
  const obj = parsed;
  if (!Array.isArray(obj.requiredSections) || obj.requiredSections.length === 0) {
    return {
      config: null,
      error: "requiredSections must be a non-empty string array."
    };
  }
  const requiredSections = obj.requiredSections.map((v) => normalizeSectionName(v)).filter((v) => v.length > 0);
  if (requiredSections.length === 0) {
    return {
      config: null,
      error: "requiredSections must contain at least one non-empty section name."
    };
  }
  if (!Array.isArray(obj.instances) || obj.instances.length === 0) {
    return {
      config: null,
      error: "instances must be a non-empty array."
    };
  }
  const requiredSet = new Set(requiredSections);
  const instances = [];
  for (const item of obj.instances) {
    let name = "";
    let promptSection = "";
    let answerSection = "";
    if (Array.isArray(item) && item.length === 2) {
      promptSection = normalizeSectionName(item[0]);
      answerSection = normalizeSectionName(item[1]);
    } else if (item && typeof item === "object") {
      const cast = item;
      name = normalizeSectionName(cast.name);
      promptSection = normalizeSectionName(cast.promptSection);
      answerSection = normalizeSectionName(cast.answerSection);
    }
    if (!promptSection || !answerSection) {
      return {
        config: null,
        error: 'Each instance must define promptSection and answerSection (or use ["A", "B"] format).'
      };
    }
    if (!requiredSet.has(promptSection) || !requiredSet.has(answerSection)) {
      return {
        config: null,
        error: `Instance (${promptSection} -> ${answerSection}) must reference sections from requiredSections.`
      };
    }
    instances.push({
      name: name || void 0,
      promptSection,
      answerSection
    });
  }
  let ai;
  if (typeof obj.ai !== "undefined") {
    if (!obj.ai || typeof obj.ai !== "object") {
      return {
        config: null,
        error: "ai must be an object when provided."
      };
    }
    const aiObj = obj.ai;
    if (aiObj.provider !== "ollama" && aiObj.provider !== "volcengine") {
      return {
        config: null,
        error: 'ai.provider must be "ollama" or "volcengine".'
      };
    }
    const model = normalizeSectionName(aiObj.model);
    if (!model) {
      return {
        config: null,
        error: "ai.model must be a non-empty string."
      };
    }
    const baseUrl = normalizeSectionName(aiObj.baseUrl) || (aiObj.provider === "volcengine" ? DEFAULT_VOLCENGINE_BASE_URL : DEFAULT_OLLAMA_BASE_URL);
    const apiKey = normalizeSectionName(aiObj.apiKey) || void 0;
    if (aiObj.provider === "volcengine" && !apiKey) {
      return {
        config: null,
        error: 'ai.apiKey must be a non-empty string when ai.provider is "volcengine".'
      };
    }
    if (!aiObj.prompts || typeof aiObj.prompts !== "object" || Array.isArray(aiObj.prompts)) {
      return {
        config: null,
        error: "ai.prompts must be an object keyed by source section and target section."
      };
    }
    const prompts = {};
    for (const [sourceRaw, targetMapRaw] of Object.entries(aiObj.prompts)) {
      const source = normalizeSectionName(sourceRaw);
      if (!requiredSet.has(source)) {
        return {
          config: null,
          error: `ai.prompts source section "${source}" must exist in requiredSections.`
        };
      }
      if (!targetMapRaw || typeof targetMapRaw !== "object" || Array.isArray(targetMapRaw)) {
        return {
          config: null,
          error: `ai.prompts.${source} must be an object keyed by target section.`
        };
      }
      const targetMap = {};
      for (const [targetRaw, promptRaw] of Object.entries(targetMapRaw)) {
        const target = normalizeSectionName(targetRaw);
        const prompt = normalizeSectionName(promptRaw);
        if (!requiredSet.has(target)) {
          return {
            config: null,
            error: `ai.prompts target section "${target}" must exist in requiredSections.`
          };
        }
        if (!prompt) {
          return {
            config: null,
            error: `ai.prompts.${source}.${target} must be a non-empty string.`
          };
        }
        targetMap[target] = prompt;
      }
      prompts[source] = targetMap;
    }
    ai = {
      provider: aiObj.provider,
      model,
      baseUrl,
      apiKey,
      prompts
    };
  }
  return {
    config: {
      requiredSections,
      instances,
      ai
    },
    error: ""
  };
}
function buildPromptFromSource(sourceContent, instruction) {
  return `${sourceContent.trim()}

${instruction.trim()}`;
}
function replaceTopLevelSectionContent(markdown, sectionName, newContent) {
  const lines = markdown.split("\n");
  const headingPattern = /^#\s+(.+)$/;
  let start = -1;
  let end = lines.length;
  for (let index = 0; index < lines.length; index++) {
    const match = lines[index].match(headingPattern);
    if (!match) continue;
    const title = match[1].trim();
    if (start === -1 && title === sectionName) {
      start = index + 1;
      continue;
    }
    if (start !== -1) {
      end = index;
      break;
    }
  }
  if (start === -1) {
    return { updatedMarkdown: markdown, updated: false };
  }
  const body = newContent.trim();
  const replacement = body ? ["", ...body.split("\n"), ""] : [""];
  const updatedLines = [
    ...lines.slice(0, start),
    ...replacement,
    ...lines.slice(end)
  ];
  return {
    updatedMarkdown: updatedLines.join("\n").replace(/\n{3,}/g, "\n\n"),
    updated: true
  };
}
var SelectionModal = class extends import_obsidian.SuggestModal {
  constructor(app, items, placeholder, toLabel, toInfo, onChoose) {
    super(app);
    this.items = items;
    this.toLabel = toLabel;
    this.toInfo = toInfo;
    this.onChoose = onChoose;
    this.setPlaceholder(placeholder);
  }
  getSuggestions(query) {
    const q = query.trim().toLowerCase();
    if (!q) return this.items;
    return this.items.filter(
      (item) => this.toLabel(item).toLowerCase().includes(q)
    );
  }
  renderSuggestion(item, el) {
    el.createDiv({ text: this.toLabel(item) });
    if (this.toInfo) {
      el.createDiv({ cls: "suggestion-note", text: this.toInfo(item) });
    }
  }
  onChooseSuggestion(item) {
    this.onChoose(item);
  }
};
var FlashcardView = class _FlashcardView extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.queue = [];
    this.idx = 0;
    this.revealed = false;
    this.queueBuildError = "";
    this.queueBuildErrorFilePath = "";
    this.activeSelection = null;
    this.keydownRegistered = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_FLASHCARD;
  }
  getDisplayText() {
    return "Flashcards";
  }
  getIcon() {
    return "brain";
  }
  async onOpen() {
    this.registerKeyboardShortcuts();
    await this.startSession();
  }
  registerKeyboardShortcuts() {
    if (this.keydownRegistered) return;
    this.keydownRegistered = true;
    this.registerDomEvent(document, "keydown", (evt) => {
      if (!this.isActiveView()) return;
      if (this.shouldIgnoreShortcut(evt.target)) return;
      if (evt.code === "Space" && !this.revealed && this.canOperateOnCurrentCard()) {
        evt.preventDefault();
        this.revealed = true;
        this.render();
        return;
      }
      if (!this.revealed || !this.canOperateOnCurrentCard()) return;
      const rating = this.keyToRating(evt);
      if (rating === null) return;
      evt.preventDefault();
      const card = this.queue[this.idx];
      void this.submitRating(card.id, rating);
    });
  }
  isActiveView() {
    const active = this.app.workspace.getActiveViewOfType(_FlashcardView);
    return active === this;
  }
  shouldIgnoreShortcut(target) {
    if (!(target instanceof HTMLElement)) return false;
    if (target.isContentEditable) return true;
    const tag = target.tagName;
    return tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT";
  }
  canOperateOnCurrentCard() {
    return !this.queueBuildError && this.queue.length > 0 && this.idx < this.queue.length;
  }
  keyToRating(evt) {
    switch (evt.code) {
      case "Digit1":
      case "Numpad1":
        return 0;
      case "Digit2":
      case "Numpad2":
        return 1;
      case "Digit3":
      case "Numpad3":
        return 2;
      case "Digit4":
      case "Numpad4":
        return 3;
      default:
        return null;
    }
  }
  /** (Re-)build the study queue and render the first card. */
  async startSession() {
    this.queueBuildError = "";
    this.queueBuildErrorFilePath = "";
    this.activeSelection = null;
    const selected = await this.plugin.selectDeckInstanceForReview();
    if (selected.error) {
      this.queueBuildError = selected.error;
      this.queue = [];
      this.idx = 0;
      this.revealed = false;
      this.render();
      return;
    }
    this.activeSelection = selected.selection;
    if (!this.activeSelection) {
      this.queueBuildError = "No deck mode selected.";
      this.queue = [];
      this.idx = 0;
      this.revealed = false;
      this.render();
      return;
    }
    await this.buildQueue(this.activeSelection);
    this.idx = 0;
    this.revealed = false;
    this.render();
  }
  // ── Queue building ─────────────────────────────────────────────────────
  async buildQueue(selection) {
    var _a, _b, _c, _d;
    const { newCardsPerDay, maxReviewsPerDay } = this.plugin.settings;
    const files = this.collectMdFiles(selection.deck.folder);
    if (files.length === 0) {
      this.queue = [];
      return;
    }
    const now = Date.now();
    const due = [];
    for (const file of files) {
      if (this.plugin.isDeckConfigFile(file)) {
        continue;
      }
      const raw = await this.app.vault.read(file);
      const sections = parseTopLevelSections(raw);
      for (const required of selection.deck.config.requiredSections) {
        if (!sections.has(required)) {
          this.queueBuildError = `Missing required section "${required}". Every flashcard note in this deck must include all required sections.`;
          this.queueBuildErrorFilePath = file.path;
          this.queue = [];
          return;
        }
      }
      const front = (_b = (_a = sections.get(selection.instance.promptSection)) == null ? void 0 : _a.trim()) != null ? _b : "";
      const back = (_d = (_c = sections.get(selection.instance.answerSection)) == null ? void 0 : _c.trim()) != null ? _d : "";
      if (!front || !back) {
        this.queueBuildError = `Cannot build card: section "${selection.instance.promptSection}" or "${selection.instance.answerSection}" is empty.`;
        this.queueBuildErrorFilePath = file.path;
        this.queue = [];
        return;
      }
      const id = this.plugin.buildCardId(selection.instanceKey, file.path);
      if (!this.plugin.cardData[id]) {
        this.plugin.cardData[id] = this.makeRecord(file.path, now);
      }
      if (this.plugin.cardData[id].dueDate <= now) {
        due.push({
          id,
          file,
          isNew: this.plugin.cardData[id].repetitions === 0,
          front,
          back
        });
      }
    }
    await this.plugin.persistData();
    const newCards = due.filter((c) => c.isNew).slice(0, newCardsPerDay);
    const reviews = due.filter((c) => !c.isNew).sort(
      (a, b) => this.plugin.cardData[a.id].dueDate - this.plugin.cardData[b.id].dueDate
    ).slice(0, maxReviewsPerDay);
    this.queue = [...newCards, ...reviews];
  }
  makeRecord(path, now) {
    return {
      path,
      repetitions: 0,
      easeFactor: DEFAULT_EASE,
      interval: 1,
      dueDate: now
    };
  }
  collectMdFiles(folder) {
    const files = [];
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        files.push(child);
      } else if (child instanceof import_obsidian.TFolder) {
        files.push(...this.collectMdFiles(child));
      }
    }
    return files;
  }
  // ── Rendering ─────────────────────────────────────────────────────────
  render() {
    const el = this.contentEl;
    el.empty();
    el.addClass("flashcard-container");
    this.refreshFontSizeVariable();
    if (this.queueBuildError) {
      this.renderMessage(
        el,
        "\u26A0\uFE0F Deck configuration error",
        this.queueBuildError
      );
      return;
    }
    if (this.queue.length === 0) {
      this.renderMessage(
        el,
        "\u{1F389} All caught up!",
        "No cards are due for review right now."
      );
      return;
    }
    if (this.idx >= this.queue.length) {
      this.renderComplete(el);
      return;
    }
    void this.renderCard(el);
  }
  renderMessage(el, title, body) {
    const wrap = el.createDiv({ cls: "flashcard-state" });
    wrap.createEl("div", { cls: "flashcard-state-icon", text: title });
    wrap.createEl("p", { cls: "flashcard-state-body", text: body });
    if (this.queueBuildErrorFilePath) {
      const link = wrap.createEl("a", {
        cls: "flashcard-error-link",
        text: `Open note: ${this.queueBuildErrorFilePath}`
      });
      link.href = "#";
      link.addEventListener("click", (evt) => {
        evt.preventDefault();
        void this.openQueueErrorFile();
      });
    }
    if (this.activeSelection) {
      const createBtn = wrap.createEl("button", {
        cls: "flashcard-btn flashcard-btn-show",
        text: "New Flashcard"
      });
      createBtn.addEventListener(
        "click",
        () => void this.createFlashcardInActiveDeck()
      );
    }
    const btn = wrap.createEl("button", {
      cls: "flashcard-btn flashcard-btn-primary",
      text: "Refresh"
    });
    btn.addEventListener("click", () => void this.startSession());
    this.renderDeckFontSizeControl(el);
  }
  async createFlashcardInActiveDeck() {
    if (!this.activeSelection) return;
    await this.plugin.createFlashcardFromDeckFolder(this.activeSelection.deck.folder);
  }
  async openQueueErrorFile() {
    if (!this.queueBuildErrorFilePath) return;
    const target = this.app.vault.getAbstractFileByPath(this.queueBuildErrorFilePath);
    if (!(target instanceof import_obsidian.TFile)) {
      new import_obsidian.Notice(`Could not find note: ${this.queueBuildErrorFilePath}`);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.openFile(target);
    this.app.workspace.revealLeaf(leaf);
  }
  renderComplete(el) {
    const wrap = el.createDiv({ cls: "flashcard-state" });
    wrap.createEl("div", { cls: "flashcard-state-icon", text: "\u{1F389}" });
    wrap.createEl("h2", { cls: "flashcard-state-title", text: "Session Complete!" });
    wrap.createEl("p", {
      cls: "flashcard-state-body",
      text: `You reviewed ${this.queue.length} card(s).`
    });
    const btn = wrap.createEl("button", {
      cls: "flashcard-btn flashcard-btn-primary",
      text: "Start New Session"
    });
    btn.addEventListener("click", () => void this.startSession());
    this.renderDeckFontSizeControl(el);
  }
  async renderCard(el) {
    var _a, _b, _c, _d;
    const card = this.queue[this.idx];
    const rec = this.plugin.cardData[card.id];
    const front = card.front;
    const back = card.back;
    const header = el.createDiv({ cls: "flashcard-header" });
    const progRow = header.createDiv({ cls: "flashcard-progress-row" });
    progRow.createSpan({
      cls: "flashcard-progress-text",
      text: `${this.idx + 1} / ${this.queue.length}`
    });
    const bar = header.createDiv({ cls: "flashcard-progress-bar" });
    bar.createDiv({
      cls: "flashcard-progress-fill",
      attr: {
        style: `width:${this.idx / this.queue.length * 100}%`
      }
    });
    const meta = header.createDiv({ cls: "flashcard-meta" });
    const typeLabel = this.activeSelection ? this.plugin.getInstanceLabel(this.activeSelection.instance) : "Deck";
    meta.createSpan({ cls: "flashcard-type-label", text: typeLabel });
    if (rec.repetitions === 0) {
      meta.createSpan({ cls: "flashcard-badge flashcard-badge-new", text: "New" });
    } else {
      meta.createSpan({
        cls: "flashcard-badge flashcard-badge-review",
        text: `${rec.interval}d`
      });
    }
    const cardEl = el.createDiv({ cls: "flashcard-card" });
    const frontSide = cardEl.createDiv({ cls: "flashcard-side" });
    frontSide.createDiv({
      cls: "flashcard-side-label",
      text: (_b = (_a = this.activeSelection) == null ? void 0 : _a.instance.promptSection) != null ? _b : "Front"
    });
    const frontContent = frontSide.createDiv({ cls: "flashcard-content" });
    await this.renderMarkdown(front, frontContent, card.file.path);
    if (this.revealed) {
      cardEl.createDiv({ cls: "flashcard-divider" });
      const backSide = cardEl.createDiv({ cls: "flashcard-side" });
      backSide.createDiv({
        cls: "flashcard-side-label",
        text: (_d = (_c = this.activeSelection) == null ? void 0 : _c.instance.answerSection) != null ? _d : "Back"
      });
      const backContent = backSide.createDiv({ cls: "flashcard-content" });
      await this.renderMarkdown(back, backContent, card.file.path);
    }
    const footer = el.createDiv({ cls: "flashcard-footer" });
    if (!this.revealed) {
      const showBtn = footer.createEl("button", {
        cls: "flashcard-btn flashcard-btn-show",
        text: "Show Answer"
      });
      showBtn.addEventListener("click", () => {
        this.revealed = true;
        this.render();
      });
    } else {
      const ratingBar = footer.createDiv({ cls: "flashcard-rating-bar" });
      const ratings = [
        ["Again", 0, "flashcard-btn-again"],
        ["Hard", 1, "flashcard-btn-hard"],
        ["Good", 2, "flashcard-btn-good"],
        ["Easy", 3, "flashcard-btn-easy"]
      ];
      for (const [label, rating, cls] of ratings) {
        const wrap = ratingBar.createDiv({ cls: "flashcard-rating-cell" });
        wrap.createDiv({
          cls: "flashcard-interval-label",
          text: formatInterval(rating, rec)
        });
        const btn = wrap.createEl("button", {
          cls: `flashcard-btn ${cls}`,
          text: label
        });
        btn.addEventListener("click", () => void this.submitRating(card.id, rating));
      }
    }
    this.renderDeckFontSizeControl(el);
  }
  getActiveDeckPath() {
    var _a, _b;
    return (_b = (_a = this.activeSelection) == null ? void 0 : _a.deck.folder.path) != null ? _b : null;
  }
  refreshFontSizeVariable() {
    const deckPath = this.getActiveDeckPath();
    const sizePx = this.plugin.getDeckFontSizePx(deckPath);
    this.contentEl.style.setProperty("--flashcard-font-size", `${sizePx}px`);
  }
  renderDeckFontSizeControl(parent) {
    const deckPath = this.getActiveDeckPath();
    if (!deckPath) return;
    const sizePx = this.plugin.getDeckFontSizePx(deckPath);
    const wrap = parent.createDiv({ cls: "flashcard-font-control" });
    wrap.createSpan({ cls: "flashcard-font-control-label", text: "Card Font" });
    const slider = wrap.createEl("input", {
      type: "range",
      cls: "flashcard-font-control-slider"
    });
    slider.min = String(MIN_CARD_FONT_SIZE_PX);
    slider.max = String(MAX_CARD_FONT_SIZE_PX);
    slider.step = "1";
    slider.value = String(sizePx);
    const valueLabel = wrap.createSpan({
      cls: "flashcard-font-control-value",
      text: `${sizePx}px`
    });
    slider.addEventListener("input", () => {
      const current = Number(slider.value);
      valueLabel.setText(`${current}px`);
      this.contentEl.style.setProperty("--flashcard-font-size", `${current}px`);
    });
    slider.addEventListener("change", () => {
      const current = Number(slider.value);
      void this.plugin.setDeckFontSizePx(deckPath, current);
    });
  }
  async renderMarkdown(markdown, el, sourcePath) {
    try {
      await import_obsidian.MarkdownRenderer.render(this.app, markdown, el, sourcePath, this);
    } catch (err) {
      console.error("Flashcards: MarkdownRenderer failed", err);
      el.createEl("pre", { text: markdown });
    }
  }
  async submitRating(cardId, rating) {
    const rec = this.plugin.cardData[cardId];
    if (rec) {
      this.plugin.cardData[cardId] = applyRating(rec, rating);
      await this.plugin.persistData();
    }
    this.idx++;
    this.revealed = false;
    this.render();
  }
};
var FlashcardsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Flashcards Settings" });
    new import_obsidian.Setting(containerEl).setName("New Cards Per Day").setDesc("Maximum number of new (unseen) cards shown per session.").addSlider(
      (slider) => slider.setLimits(1, 100, 1).setValue(this.plugin.settings.newCardsPerDay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.newCardsPerDay = value;
        await this.plugin.persistData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max Reviews Per Day").setDesc("Maximum number of due review cards shown per session.").addSlider(
      (slider) => slider.setLimits(1, 500, 1).setValue(this.plugin.settings.maxReviewsPerDay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxReviewsPerDay = value;
        await this.plugin.persistData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Card Font Size").setDesc(
      "Fallback font size for decks that don't have a deck-specific size set in the Flashcards view."
    ).addSlider(
      (slider) => slider.setLimits(MIN_CARD_FONT_SIZE_PX, MAX_CARD_FONT_SIZE_PX, 1).setValue(this.plugin.settings.cardFontSizePx).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.cardFontSizePx = value;
        this.plugin.applyCardFontSizeToOpenViews();
        await this.plugin.persistData();
      })
    );
    containerEl.createEl("h3", { text: "Deck Config File" });
    const desc = containerEl.createEl("p", {
      cls: "setting-item-description"
    });
    desc.textContent = "Each deck folder must contain a config file named <deck_dir>.flashcards in JSON format.";
    const ul = containerEl.createEl("ul");
    ul.createEl("li", {
      text: "Config filename must match folder name, e.g. deck_dir/deck_dir.flashcards."
    });
    ul.createEl("li", {
      text: "requiredSections defines mandatory H1 sections in every card note."
    });
    ul.createEl("li", {
      text: "instances define prompt/answer section pairs, each becoming a study mode."
    });
    ul.createEl("li", {
      text: "Nested decks are not allowed: if a deck folder has a child deck folder, the plugin will stop and show an error."
    });
    containerEl.createEl("h4", { text: "Example" });
    containerEl.createEl("pre").createEl("code", {
      text: [
        "{",
        '  "requiredSections": ["A", "B", "C"],',
        '  "instances": [',
        '    ["A", "B"],',
        '    { "name": "B-to-C", "promptSection": "B", "answerSection": "C" }',
        "  ]",
        "}"
      ].join("\n")
    });
    containerEl.createEl("h4", { text: "Card Note Example" });
    containerEl.createEl("pre").createEl("code", {
      text: [
        "# A",
        "Prompt content",
        "",
        "# B",
        "Expected answer",
        "",
        "# C",
        "Extra context"
      ].join("\n")
    });
  }
};
var FlashcardsPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    /** In-memory card records, kept in sync with data.json. */
    this.cardData = {};
    this.aiStatusBarEl = null;
  }
  logDebug(message, meta) {
    if (typeof meta === "undefined") {
      console.info(`${DEBUG_PREFIX} ${message}`);
      return;
    }
    console.info(`${DEBUG_PREFIX} ${message}`, meta);
  }
  registerDeckFolderMenuHook() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        this.logDebug("file-menu fired", {
          path: file.path,
          type: file instanceof import_obsidian.TFolder ? "folder" : "file"
        });
        this.tryAddNewFlashcardMenuItem(menu, file, "file-menu");
      })
    );
    const workspaceAny = this.app.workspace;
    this.registerEvent(
      workspaceAny.on("files-menu", (menu, files) => {
        if (!Array.isArray(files)) return;
        const first = files[0];
        const cast = first;
        this.logDebug("files-menu fired", {
          count: files.length,
          firstPath: cast == null ? void 0 : cast.path,
          firstType: cast instanceof import_obsidian.TFolder ? "folder" : "file"
        });
        if (!cast || files.length !== 1) return;
        this.tryAddNewFlashcardMenuItem(menu, cast, "files-menu");
      })
    );
  }
  registerAiCompletionUi() {
    this.aiStatusBarEl = this.addStatusBarItem();
    this.aiStatusBarEl.addClass("mod-clickable");
    this.aiStatusBarEl.setText("AI Complete");
    this.aiStatusBarEl.addEventListener("click", () => void this.completeCurrentFlashcardWithAi());
    this.addCommand({
      id: "ai-complete-current-flashcard",
      name: "AI Complete Current Flashcard",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        const canRun = file instanceof import_obsidian.TFile && file.extension === "md" && !this.isDeckConfigFile(file);
        if (!checking && canRun) {
          void this.completeCurrentFlashcardWithAi();
        }
        return canRun;
      }
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.updateAiStatusBarVisibility())
    );
    this.registerEvent(
      this.app.workspace.on("file-open", () => this.updateAiStatusBarVisibility())
    );
    this.updateAiStatusBarVisibility();
  }
  updateAiStatusBarVisibility() {
    if (!this.aiStatusBarEl) return;
    const activeFile = this.app.workspace.getActiveFile();
    const visible = activeFile instanceof import_obsidian.TFile && activeFile.extension === "md" && !this.isDeckConfigFile(activeFile);
    this.aiStatusBarEl.style.display = visible ? "" : "none";
  }
  tryAddNewFlashcardMenuItem(menu, file, sourceEvent) {
    var _a;
    if (!(file instanceof import_obsidian.TFolder)) {
      return;
    }
    const configFile = this.getDeckConfigFileForFolder(file);
    this.logDebug("folder context detected", {
      sourceEvent,
      folder: file.path,
      configFile: (_a = configFile == null ? void 0 : configFile.path) != null ? _a : null
    });
    const menuAny = menu;
    menuAny.addItem(
      (item) => item.setTitle("New Flashcard").setIcon("plus-circle").onClick(() => {
        var _a2;
        this.logDebug("New Flashcard clicked", {
          folder: file.path,
          configFile: (_a2 = configFile == null ? void 0 : configFile.path) != null ? _a2 : null
        });
        void this.createFlashcardFromDeckFolder(file);
      })
    );
  }
  async onload() {
    var _a, _b;
    const stored = await this.loadData();
    const merged = Object.assign({}, DEFAULT_SETTINGS, (_a = stored == null ? void 0 : stored.settings) != null ? _a : {});
    this.settings = {
      newCardsPerDay: merged.newCardsPerDay,
      maxReviewsPerDay: merged.maxReviewsPerDay,
      cardFontSizePx: Math.max(
        MIN_CARD_FONT_SIZE_PX,
        Math.min(MAX_CARD_FONT_SIZE_PX, Number(merged.cardFontSizePx) || DEFAULT_SETTINGS.cardFontSizePx)
      ),
      deckFontSizePxByPath: typeof merged.deckFontSizePxByPath === "object" && merged.deckFontSizePxByPath ? Object.fromEntries(
        Object.entries(merged.deckFontSizePxByPath).map(([path, size]) => [path, Number(size)]).filter(
          ([path, size]) => typeof path === "string" && path.length > 0 && Number.isFinite(size) && size >= MIN_CARD_FONT_SIZE_PX && size <= MAX_CARD_FONT_SIZE_PX
        )
      ) : {}
    };
    this.cardData = (_b = stored == null ? void 0 : stored.cards) != null ? _b : {};
    this.registerView(
      VIEW_TYPE_FLASHCARD,
      (leaf) => new FlashcardView(leaf, this)
    );
    this.addRibbonIcon(
      "brain",
      "Open Flashcards",
      () => void this.openStudyView()
    );
    this.addCommand({
      id: "open-flashcard-deck",
      name: "Open Flashcard Deck",
      callback: () => void this.openStudyView()
    });
    this.logDebug("plugin loaded", { version: this.manifest.version });
    this.registerDeckFolderMenuHook();
    this.registerAiCompletionUi();
    this.applyCardFontSizeToOpenViews();
    this.addSettingTab(new FlashcardsSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_FLASHCARD);
  }
  /** Save both settings and card data atomically. */
  async persistData() {
    await this.saveData({
      settings: this.settings,
      cards: this.cardData
    });
  }
  /** Open (or reveal) the flashcard study panel. */
  async openStudyView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_FLASHCARD);
    if (existing.length > 0) {
      this.applyCardFontSizeToOpenViews();
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_FLASHCARD, active: true });
    this.applyCardFontSizeToOpenViews();
    workspace.revealLeaf(leaf);
  }
  applyCardFontSizeToOpenViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_FLASHCARD)) {
      const view = leaf.view;
      if (view instanceof FlashcardView) {
        view.refreshFontSizeVariable();
      }
    }
  }
  async getDeckDefinitionForNote(file) {
    if (this.isDeckConfigFile(file)) {
      return {
        deck: null,
        error: "Deck config files cannot be AI-completed as flashcard notes."
      };
    }
    const discovered = await this.discoverDeckDefinitions();
    if (discovered.error) {
      return { deck: null, error: discovered.error };
    }
    const deck = discovered.decks.filter((candidate) => file.path.startsWith(`${candidate.folder.path}/`)).sort((a, b) => b.folder.path.length - a.folder.path.length)[0];
    if (!deck) {
      return {
        deck: null,
        error: `The active note is not inside a configured flashcards deck: ${file.path}`
      };
    }
    return { deck, error: "" };
  }
  async generateWithOllama(ai, prompt) {
    const baseUrl = (ai.baseUrl || DEFAULT_OLLAMA_BASE_URL).replace(/\/$/, "");
    const response = await fetch(`${baseUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: ai.model,
        prompt,
        stream: false
      })
    });
    if (!response.ok) {
      throw new Error(`Ollama request failed with status ${response.status}`);
    }
    const payload = await response.json();
    const output = typeof payload.response === "string" ? payload.response.trim() : "";
    if (!output) {
      throw new Error("Ollama returned empty content.");
    }
    return output;
  }
  async generateWithVolcEngine(ai, prompt) {
    var _a, _b, _c;
    const baseUrl = (ai.baseUrl || DEFAULT_VOLCENGINE_BASE_URL).replace(/\/$/, "");
    if (!ai.apiKey) {
      throw new Error("VolcEngine API key is missing.");
    }
    const response = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ai.apiKey}`
      },
      body: JSON.stringify({
        model: ai.model,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      })
    });
    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `VolcEngine request failed with status ${response.status}${errorText ? `: ${errorText}` : ""}`
      );
    }
    const payload = await response.json();
    const output = typeof ((_c = (_b = (_a = payload.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) === "string" ? payload.choices[0].message.content.trim() : "";
    if (!output) {
      throw new Error("VolcEngine returned empty content.");
    }
    return output;
  }
  async generateAiOutput(ai, prompt) {
    switch (ai.provider) {
      case "ollama":
        return this.generateWithOllama(ai, prompt);
      case "volcengine":
        return this.generateWithVolcEngine(ai, prompt);
      default:
        throw new Error(`Unsupported AI provider: ${ai.provider}`);
    }
  }
  findAiCompletionPlan(deck, sections) {
    var _a, _b, _c, _d, _e;
    if (!deck.config.ai) {
      return { error: `Deck ${deck.folder.path} has no ai configuration.` };
    }
    let sourceSection = "";
    let sourceContent = "";
    for (const section of deck.config.requiredSections) {
      const content = (_b = (_a = sections.get(section)) == null ? void 0 : _a.trim()) != null ? _b : "";
      if (content) {
        sourceSection = section;
        sourceContent = content;
        break;
      }
    }
    if (!sourceSection) {
      return { error: "No source section has content yet. Fill the first source section before using AI Complete." };
    }
    const targetPrompts = deck.config.ai.prompts[sourceSection];
    if (!targetPrompts) {
      return {
        error: `No AI prompt mapping is configured from section "${sourceSection}".`
      };
    }
    for (const targetSection of deck.config.requiredSections) {
      if (targetSection === sourceSection) continue;
      const targetContent = (_d = (_c = sections.get(targetSection)) == null ? void 0 : _c.trim()) != null ? _d : "";
      if (targetContent) continue;
      const instruction = (_e = targetPrompts[targetSection]) == null ? void 0 : _e.trim();
      if (instruction) {
        return {
          sourceSection,
          sourceContent,
          targetSection,
          instruction,
          aI: deck.config.ai
        };
      }
    }
    return {
      error: `No AI prompt mapping found from section "${sourceSection}" to an empty target section.`
    };
  }
  async completeCurrentFlashcardWithAi() {
    const file = this.app.workspace.getActiveFile();
    if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") {
      new import_obsidian.Notice("Open a markdown flashcard note before using AI Complete.");
      return;
    }
    const deckResult = await this.getDeckDefinitionForNote(file);
    if (!deckResult.deck) {
      new import_obsidian.Notice(deckResult.error);
      return;
    }
    const raw = await this.app.vault.read(file);
    const sections = parseTopLevelSections(raw);
    const plan = this.findAiCompletionPlan(deckResult.deck, sections);
    if ("error" in plan) {
      new import_obsidian.Notice(plan.error);
      return;
    }
    const prompt = buildPromptFromSource(plan.sourceContent, plan.instruction);
    new import_obsidian.Notice(`AI completing ${plan.targetSection} from ${plan.sourceSection}...`);
    try {
      const output = await this.generateAiOutput(plan.aI, prompt);
      const updated = replaceTopLevelSectionContent(raw, plan.targetSection, output);
      if (!updated.updated) {
        new import_obsidian.Notice(`Could not locate section ${plan.targetSection} in the current note.`);
        return;
      }
      await this.app.vault.modify(file, updated.updatedMarkdown);
      new import_obsidian.Notice(`Filled section ${plan.targetSection} with AI output.`);
    } catch (error) {
      console.error(`${DEBUG_PREFIX} AI completion failed`, error);
      new import_obsidian.Notice(`AI completion failed: ${error instanceof Error ? error.message : "Unknown error"}`);
    }
  }
  getDeckFontSizePx(deckPath) {
    var _a;
    if (!deckPath) return this.settings.cardFontSizePx;
    return (_a = this.settings.deckFontSizePxByPath[deckPath]) != null ? _a : this.settings.cardFontSizePx;
  }
  async setDeckFontSizePx(deckPath, sizePx) {
    const clamped = Math.max(
      MIN_CARD_FONT_SIZE_PX,
      Math.min(MAX_CARD_FONT_SIZE_PX, Math.round(sizePx))
    );
    this.settings.deckFontSizePxByPath[deckPath] = clamped;
    this.applyCardFontSizeToOpenViews();
    await this.persistData();
  }
  buildCardId(instanceKey, notePath) {
    return `${instanceKey}::${notePath}`;
  }
  isDescendantFolder(parentPath, childPath) {
    if (parentPath === childPath) return false;
    if (parentPath === "") return childPath !== "";
    return childPath.startsWith(`${parentPath}/`);
  }
  getInstanceLabel(instance) {
    return instance.name || `${instance.promptSection} -> ${instance.answerSection}`;
  }
  getInstanceKey(deckPath, instance) {
    return `${deckPath}::${instance.promptSection}->${instance.answerSection}`;
  }
  isDeckConfigFileName(fileName, folderName) {
    const lowerName = fileName.toLowerCase();
    const lowerFolder = folderName.toLowerCase();
    return lowerName === `${lowerFolder}.flashcards` || lowerName === `${lowerFolder}.flashcards.md`;
  }
  isDeckConfigFile(file) {
    if (!file.parent) return false;
    return this.isDeckConfigFileName(file.name, file.parent.name);
  }
  getDeckConfigFileForFolder(folder) {
    for (const child of folder.children) {
      if (!(child instanceof import_obsidian.TFile)) continue;
      if (this.isDeckConfigFileName(child.name, folder.name)) {
        return child;
      }
    }
    return null;
  }
  async getDeckDefinitionForFolder(folder) {
    const configFile = this.getDeckConfigFileForFolder(folder);
    if (!configFile) {
      return {
        deck: null,
        error: `Missing config file ${folder.name}.flashcards in ${folder.path}`
      };
    }
    const raw = await this.app.vault.read(configFile);
    const parsed = parseDeckConfig(raw);
    if (!parsed.config) {
      return {
        deck: null,
        error: `Config error in ${configFile.path}: ${parsed.error}`
      };
    }
    return {
      deck: {
        folder,
        configFile,
        config: parsed.config
      },
      error: ""
    };
  }
  createFlashcardTemplate(requiredSections) {
    return requiredSections.map((section) => `# ${section}
`).join("\n");
  }
  getUniqueNewFlashcardPath(folder) {
    const base = `${folder.path}/New Flashcard`;
    let candidate = `${base}.md`;
    let n = 2;
    while (this.app.vault.getAbstractFileByPath(candidate)) {
      candidate = `${base} ${n}.md`;
      n++;
    }
    return candidate;
  }
  async createFlashcardFromDeckFolder(folder) {
    const deckResult = await this.getDeckDefinitionForFolder(folder);
    if (!deckResult.deck) {
      new import_obsidian.Notice(deckResult.error);
      return;
    }
    const notePath = this.getUniqueNewFlashcardPath(folder);
    const content = this.createFlashcardTemplate(
      deckResult.deck.config.requiredSections
    );
    try {
      const created = await this.app.vault.create(notePath, content);
      const leaf = this.app.workspace.getLeaf("tab");
      await leaf.openFile(created);
      new import_obsidian.Notice(`Created flashcard: ${created.path}`);
    } catch (error) {
      console.error("Flashcards: failed to create note", error);
      new import_obsidian.Notice("Failed to create flashcard note.");
    }
  }
  async discoverDeckDefinitions() {
    const configFiles = this.app.vault.getFiles().filter((f) => this.isDeckConfigFile(f));
    if (configFiles.length === 0) {
      return {
        decks: [],
        error: "No deck config found. Add <deck_dir>.flashcards in your deck folder."
      };
    }
    const decks = [];
    for (const configFile of configFiles) {
      if (!(configFile.parent instanceof import_obsidian.TFolder)) continue;
      const raw = await this.app.vault.read(configFile);
      const parsed = parseDeckConfig(raw);
      if (!parsed.config) {
        return {
          decks: [],
          error: `Config error in ${configFile.path}: ${parsed.error}`
        };
      }
      decks.push({
        folder: configFile.parent,
        configFile,
        config: parsed.config
      });
    }
    decks.sort((a, b) => a.folder.path.length - b.folder.path.length);
    for (let i = 0; i < decks.length; i++) {
      for (let j = i + 1; j < decks.length; j++) {
        if (this.isDescendantFolder(decks[i].folder.path, decks[j].folder.path)) {
          return {
            decks: [],
            error: `Nested deck folders are not allowed: "${decks[i].folder.path}" contains child deck "${decks[j].folder.path}".`
          };
        }
      }
    }
    return { decks, error: "" };
  }
  async pickOne(items, placeholder, toLabel, toInfo) {
    if (items.length === 0) return null;
    if (items.length === 1) return items[0];
    return await new Promise((resolve) => {
      let resolved = false;
      const modal = new SelectionModal(
        this.app,
        items,
        placeholder,
        toLabel,
        toInfo,
        (item) => {
          resolved = true;
          resolve(item);
        }
      );
      const close = modal.onClose.bind(modal);
      modal.onClose = () => {
        close();
        if (!resolved) resolve(null);
      };
      modal.open();
    });
  }
  async selectDeckInstanceForReview() {
    const discovered = await this.discoverDeckDefinitions();
    if (discovered.error) {
      return { selection: null, error: discovered.error };
    }
    const deck = await this.pickOne(
      discovered.decks,
      "Select a deck folder",
      (item) => item.folder.path,
      (item) => item.configFile.name
    );
    if (!deck) {
      return { selection: null, error: "Deck selection cancelled." };
    }
    const instance = await this.pickOne(
      deck.config.instances,
      "Select a deck mode",
      (item) => this.getInstanceLabel(item),
      (item) => `${item.promptSection} -> ${item.answerSection}`
    );
    if (!instance) {
      return { selection: null, error: "Deck mode selection cancelled." };
    }
    return {
      selection: {
        deck,
        instance,
        instanceKey: this.getInstanceKey(deck.folder.path, instance)
      },
      error: ""
    };
  }
};
